### ISSUE TITLE
Prioritize CF vs DEVO

### ISSUE THREAD

**Issue by jandersson** [rpherbig/dr-scripts#1020]
Some users think it would be nice if CF could be prioritized over DEVO in certain cases. Currently the wound severity is taken from this table https://elanthipedia.play.net/Wounds so that should be taken into account. Bleeding can be detected but its not currently done as part of the "am i wounded?" necro healing check.

**Comment by jandersson** [comment]
One possibility is to run CF when checked against these bleeding levels:
Tended
Clotted
Slight
Light
Moderate
Bad
Very Bad
Heavy
Very Heavy
Severe
Very Severe
Profuse
Very Profuse
Gushing
Massive Stream
Uncontrollable
Unbelievable
Beyond Measure
Death Awaits

**Comment by cynesis** [comment]
Consume Flesh vs Devour comparison is the same as Heal Wounds vs Heal: The former provides mana-efficient healing to a specific location (external/internal), whereas the latter provides generalized healing based on wound severity up to four locations (locations chosen by the game).

Without going into mana maintenance issues, it stands to reason that CF should be utilized in a few cases:
1. Single wound
2. Serious wound (bleeding level greater than light, etc.)

Additionally, CF can be cast multiple times on a single corpse. From Elanthipedia:

> The number of times Consume Flesh may be cast on a single corpse is based on your Thanatology skill, and you gain one additional use every 75 ranks up to a total of 5 uses.

For Devour, using it to broadly heal down several wounds is the general use-case.

Until certain magic ranks are achieved, utilizing Devour as a primary source of healing is not sustainable. However, Devour also heals wounds that can not be seen via the HEALTH command (such as nerve wounds below a certain threshold).

Since you can Consume Flesh up to 5 times per corpse, it is likely that CF can be used for maintaining a woundless state while Devour can be used as a sort of general cleanup if wounds begin spiraling out of control. This is obviously a function of what creature a player hunts versus said player's combat ranks.

It should be noted that if non-combat healing is to be implemented, Devour can use the materials harvested from the Harvest ritual for healing. That is, having combat-trainer save decent quality (good, flawless, etc) materials for later clean-up (added to safe-room perhaps) could be useful. Especially since Necromancers do not have a method to handle disease at the moment.

Simplifying CF vs Devour is not simple. But a good starting point is CF for single wounds or severe wounds (multiple casts for multiple severe wounds) and Devour for general clean-up, during or after combat.

**Comment by jandersson** [comment]
I like the idea healing severe wounds with CF. Do you think a cast of CF for a single wound instance would neglect the "invisible" wounds?

**Comment by cynesis** [comment]
Assuming the cast is successful, a single cast of CF against nerves will fully heal invisible wounds. The possibility that it doesn't suggests that the wound is so severe that it would show up under the HEALTH command to begin with.

Note that a single cast of Devour will likely do the same, without the need to specify the wound location.

**Comment by jandersson** [comment]
Sorry, I mean wounds other than the targeted one. I'm imagining the scenario where you build up several hidden wounds, one becomes visible, CF targets that whereas DEVO targets 3 others

**Comment by Zhennlash** [comment]
I would like to note that at present, CF is only being used once per corpse (as far as I have been able to observe).

**Comment by jandersson** [comment]
I can make a second issue for the multiple CF casts, thats kinda been overdue anyway

**Comment by jandersson** [comment]
Devour heals just fine.
