### ISSUE TITLE
Add Priority Hunting Targets

### ISSUE THREAD

**Issue by jayRyan24** [rpherbig/dr-scripts#1168]
Set up a Priority Hunting Target, such that you will kill them first and switch immediately when they enter the room. An example of why this is needed could be the random Tusky in Stompers that just gored my thigh for a 9/23.

**Comment by intangibles** [comment]
First step will be adding creature long descriptions and creature adjectives.  See #1410.  

Adding a priority target switch will be more complicated.  You generally want to kill the target you are facing first since it can have arrows or lodged items.  Most of the combat script is setup this way.   

Target_enemy current works for spells which can assist in this.  But it only currently compares against npc nouns.  YAML: 
target_enemy: beast

    .select { |spell| spell['target_enemy'] ? game_state.npcs.include?(spell['target_enemy']) : true }
