### ISSUE TITLE
Create process for overwriting base YAMLS (other then base.yaml)

### ISSUE THREAD

**Issue by brycole** [rpherbig/dr-scripts#1428]
I'm not sure if this exists, but a process for overwriting pieces of other base.yamls would be useful.

For example, base-hunting.yaml has rooms in a certain order, usually of spawn rate, but subject to the creators discretion. However, if the first room is elemental 1/15, then elemental users will not want to use that room.  So their room order preference will change.  This is not really something the base-hunting.yaml can predict.

So I was thinking we could either integrate into setup.yaml or another file.

So if i wanted to overwrite a certain section of base-hunting yaml, hopefully it would just follow the same formating.

base-hunting.yaml
```
hunting_zones:
  # https://elanthipedia.play.net/Rat 0-30
  rats:
  - 6049
  - 6048
  - 6047
  - 6046
  - 6050
  - 6053
  - 6054
```

player overrides
```
hunting_zones:
  # https://elanthipedia.play.net/Rat 0-30
  rats:
  - 6054
  - 6053
  - 6047
```

**Comment by rpherbig** [comment]
Settings in your YAML file will overwrite whatever is in a base file.

Also note that the mana of a room changes over time, so there will still be fluctuations.

**Comment by intangibles** [comment]
so if i put

**Comment by intangibles** [comment]
Below is the base-hunting.yaml.

```
hunting_zones:
  grass_eels:
  - 1492
  - 1495
  - 1491
  - 1490
  - 1493
  - 1494
```


If I put the below in my setup.yaml, the hunting script does not move to the changed locations.  Is there something else going? (There are no errors that pop in the YAML.)

```
hunting_zones:
 grass_eels:
 - 1494
 - 1493
 - 1495
```

**Comment by skyleronken** [comment]
So the issue is  here in hunting buddy:

```
    data = get_data('hunting')
    @escort_zones = data.escort_zones
    @hunting_zones = data.hunting_zones
 
    ...

def find_hunting_room?(zone_name)
    UserVars.friends = @settings.hunting_buddies || []
    if rooms = @hunting_zones[zone_name]
   
```

There is no opportunity for user settings to override that which is imported from base-hunting.yaml.

If we really want to add this functionality, we ought to put a check in find_hunting_room() to see if a :room: attribute is set within the that hunting_info entry. 

However, I don't really see the value in this functionality because of the nature of mana.

@intangibles What do you think about functionality that defines a minimum mana level for  a room you choose to hunt in? I.e if set, you would perceive, then move on until you found a room that was empty and met your standard for mana?

**Comment by jandersson** [comment]
One possibility is to use `transform_settings` in dependency, its currently used to merge user data with spell data and combine loot subtractions/additions into a single lootables list.

**Comment by rcuhljr** [comment]
This has come up several times. Basically I haven't seen a convincing argument yet that the other base files should be overrideable. Each thing I've seen suggested would be better handled as an adjustable setting in a script. For example mana, it would be better to add an option to specify minimal acceptable mana since levels fluctuate over time and let the hunting script skip bad mana rooms.

**Comment by intangibles** [comment]
@skyleronken The mana idea is a pretty good one. I can come up with a few minor reasons why I'd want to change rooms not based on mana, but they are minor and don't really warrant a a change.

The only issue i would be concerned about is a mana toggle adding some inefficiency to the hunting areas. e.g. PP over 6 rooms @ 8 seconds to get the 7th room.  Especially when you know the 7th room has the good mana. But I'm less concerned about this because people need to train attunement anyways.

**Comment by MahtraDR** [comment]
@rpherbig It's not the original issue, but https://github.com/rpherbig/dr-scripts/pull/1503 addresses the direction the discussion went to (and died) in 2017. Maybe close? The conversation is worthwhile, but since it hasn't been picked up in 4 years, is it worth keeping this open?
