### ISSUE TITLE
Change to ;workorders - trash items not high quality enough

### ISSUE THREAD

**Issue by jonathan-stricker** [rpherbig/dr-scripts#1475]
I'm doing some forging work orders for the first time, no techs yet so often I don't make them high quality enough to go into the logbook. It just stores those items in my storage container and they pile up, can they be thrown in the trash instead? Thanks, --Reithir

**Comment by MahtraDR** [comment]
@rpherbig We should be able to close this. The issue here is known, and tends to be related to tools not being repaired, which in turn causes a loss of quality on the end product, which in turn means you can't bundle with the logbook. Dart's already looking at a more informative error when this happens.
