### ISSUE TITLE
add rock guardian death messaging to combat

### ISSUE THREAD

**Issue by hwoo79** [rpherbig/dr-scripts#148]
combat doesn't detect the death of rock guardians, therefore doesn't go to loot.

rock guardian death messaging:

A rock guardian collapses into a pile of stone rubble.

**Comment by rpherbig** [comment]
Combat trainer does not key off of any death messaging. It loots based on
DRRoom.dead_npcs (on phone, can't look up exact name).

Can you echo the output of that call in a room with a dead rock guardian?

**Comment by hwoo79** [comment]
how?  this might be something on my end.

combat is not pulling all the settings from yaml, it's not dancing, not using debilitation, not fatigue regen.

**Comment by rpherbig** [comment]
The easy way to test this would be to make a new script 'temp.lic' that contains:
```
echo "DRRoom.dead_npcs: #{DRRoom.dead_npcs}"
```

Then you can run ;temp when a dead rock guardian is in the room.

However, if you aren't dancing,etc. then this seems like a deeper problem with your config. That would be easier to debug when we can talk in-game, instead of asynchronously here.

**Comment by hwoo79** [comment]
my problem, false start, 5 yards, replay the down.
