### ISSUE TITLE
put a switch for alternate "skinning" in combat

### ISSUE THREAD

**Issue by hwoo79** [rpherbig/dr-scripts#151]
sorry, submitted by accident.

**Comment by rpherbig** [comment]
Could you elaborate on what you mean by this?

**Comment by hwoo79** [comment]
have the script check for a yaml setting, let's call it 'necro' when it goes into the skinning section/method.

if necro: true, 
then do perform preserve on deadcritter, perform dissect on deadcritter
else do normal skinning settings.

**Comment by rcuhljr** [comment]
Ok, here is where we copy in the variables into combat-trainer from the setup. I've highlighted skinning.

https://github.com/rpherbig/dr-scripts/blob/master/combat-trainer.lic#L757-L760

Those are passed into the [loot process](https://github.com/rpherbig/dr-scripts/blob/master/combat-trainer.lic#L142-L233) from [here.](https://github.com/rpherbig/dr-scripts/blob/master/combat-trainer.lic#L790)


I'd look at [dispose_body](https://github.com/rpherbig/dr-scripts/blob/master/combat-trainer.lic#L185-L193) and make your alternate check there, call a new method instead of skinning when there's a body.

**Comment by hwoo79** [comment]
So, here is the check for skinning:
check_skinning(DRRoom.dead_npcs.first) if @skin

I should put my check for the alternate disposal method before it then this check as an else, right?

**Comment by rcuhljr** [comment]
yeah I'd turn it into something like
```
if @necro
 do_necro_things
elsif @skin
 do_skin_things
end

**Comment by hwoo79** [comment]
Can you give my branch-1 a look-see and tell me if I'm on the right track?

**Comment by rcuhljr** [comment]
Switch to that branch and click the 'make a pull request' button. That will create an open pull request that I can make comments easily on a per line basis, and as you add changes to that branch it will update the pull request with the changes.

**Comment by rpherbig** [comment]
@rcuhljr @hwoo79 Can this be closed due to ed360f473a6958e8b305707ab98576553d485a83 ?

**Comment by hwoo79** [comment]
yeah, i want to develop some 'enhanced' functionality at some point, but this issue is satisfied.
