### ISSUE TITLE
Combat-trainer should not exit if necromancer

### ISSUE THREAD

**Issue by jandersson** [rpherbig/dr-scripts#1546]
If player health is below 40% and is a necromancer, the script will quit the game. However this is how they could potentially heal themselves and get above 40%

**Comment by wscherer420** [comment]
It would be great if the ;safe script could work for Necro's by activating a hunting file that's created specifically to heal.  So for example, ;safe is activated, it does a health check, and if necessary it picks the file i've marked, for example: Italshan-Safe.  Which i would setup to run me to a hunting ground specifically for healing.  A sample of this hunting file could be setup and be written so that it only focuses on healing.  No other training like perception, appraisal, etc...  

;safe could stay active and do health checks until it recognizes you are completely healed, then it would kill the script and move on?

**Comment by rpherbig** [comment]
That sounds similar to #1562

**Comment by wscherer420** [comment]
You're right!  Thank you.

**Comment by jandersson** [comment]
Its in reference to https://github.com/rpherbig/dr-scripts/blob/master/combat-trainer.lic#L621 
If the only way to heal is by running combat-trainer, but you exit the game if youre below 40% health, you can't get healed

**Comment by wscherer420** [comment]
That's accurate.  In that situation, to heal I need to do it manually without activating any scripts.

**Comment by jandersson** [comment]
I've commented out the line and my necromancer can self-heal if seriously injured using combat-trainer

**Comment by wscherer420** [comment]
In the base file?  I still want it to exit me sometimes.  I want it all! lol.

**Comment by jandersson** [comment]
This line: https://github.com/rpherbig/dr-scripts/blob/master/combat-trainer.lic#L621  I've been relying on `afk.lic` to handle vitality logouts. I wonder if `combat-trainer.lic` could use a setting like `combat_trainer_exit_on_low_health`.

**Comment by wscherer420** [comment]
It may be better if it could be done when you activate the script...like ;combat-trainer heal for example.  Then it overrides the vitality rules.  This way combat-trainer normally could still exit you if you aren't present to monitor the situation.

**Comment by jandersson** [comment]
Another possible solution could be to not exit if `necromancer_healing` is defined

**Comment by jandersson** [comment]
That makes sense to me

**Comment by rpherbig** [comment]
I think a worst case scenario would be you have necro talking defined and
are still going low despite healing.

Also, if you define healing in a separate YAML file then we won't see it
here

**Comment by rpherbig** [comment]
We should poll and see if anyone relies on the logout behavior of combat
trainer and does NOT use afk. Regardless of guild, maybe it can be removed.

**Comment by intangibles** [comment]
I imagine a lot of people use ,combat-trainers logoff function since ,afk isn't autostarted.  Personally I'd be in favor of moving the functionality away from ,afk since it can have a negative connotation.  I'd be in favor of moving items to an all in one "status-monitor" script that has ,afk functionality.  (I know we have a status-monitor script already)

**Comment by intangibles** [comment]
@wscherer420 

I'm going to work on my PR this week.  It does precisely what you ask for, its just not hooked to safe-room. It's also quite hacky so I want to redo some of the functionality.

You can achieve similar results in a before/after script by running a 5 minute duration "heal" back YAML with using ,huntingbuddy heal.

Combat-trainer isn't quite designed for this so I'll get the basics in, and then we can refine from there.  (It wastes a lot of time, even after fully healed.)
