### ISSUE TITLE
Astrology script and backfiring spells

### ISSUE THREAD

**Issue by Missah** [rpherbig/dr-scripts#1614]
If any of the prebuff spells (in my case pg, aus, rtr, dc0 for astrology backfire...it can affect how much astrology is learned.

[astrology]>cast
You close your eyes and take several slow, calming breaths.
The mental strain of this pattern is considerably eased by your ritual focus.
Your spell barely backfires.

Can some sort of check be added to confirm these spells have been successfully cast?

Thank you!

**Comment by intangibles** [comment]
I think the easiest and most efficient way would be to manage this as a player... but I do see a decent option.

Since dependency doesn't currently track known spells, you couldn't simply add a binary check because players may learn different spells at different times.  The best way would probably be to add similar functionality to combat_trainer buff_spells.  That way players could add spells themselves and take advantage of that functionality.

The large barrier here is combat_trainer has a lot of functionality unique which makes it hard to pull the code out.  I'll poke around and see how hard it might be to convert.

**Comment by rpherbig** [comment]
@intangibles Buffs already have to be defined to be cast before training a given skill. Right now we only attempt to cast each spell once.

I _think_ @Missah is asking for us to recast if it fails. I suggest instead lowering the mana slightly (since these spells are intended to support the skill being trained, not necessarily train a magic skill themselves).

**Comment by rpherbig** [comment]
Here's example: https://github.com/rpherbig/dr-scripts/blob/master/profiles/Paeriluno-setup.yaml#L200-L205

**Comment by intangibles** [comment]
@rpherbig 
Yeah, i definitely agree managing it as a player would be a good idea.  But at the same time, does astrology_buffs account for items at say, 5 duration that drop in the middle of training?

I mentioned this over in #1639, but I could see a buff_spells type function that constantly checked for dropped spells being useful.

**Comment by Missah** [comment]
Yes, a recast if the buff fails would be perfect, if it's doable.

**Comment by rpherbig** [comment]
@intangibles We attempt to account for that by always casting each buff, regardless of if it is already active. See #1063 for some discussion on that.

**Comment by jandersson** [comment]
I'd like a setting that didn't recast astro buffs if theyre already present

**Comment by jandersson** [comment]
I'm worried that making it recast the buffs will just put you in an endless casting loop, where you backfire and build up nerve damage, making the next recast even more difficult. I think the best solution is to not shoot for the most potent casts. From my understanding you can do piercing gaze at minimum potency and it works just fine at piercing cloud cover.

**Comment by rpherbig** [comment]
I'm with @jandersson on this one. If I accidentally set the prep too high, I'd rather fail the cast once than spend a while taking even more nerve damage.

**Comment by intangibles** [comment]
@jandersson Well, I don't think that should necessarily be a consideration because people manage to avoid that problem with combat buffs.

However, after some pondering I agree that I don't think a continual buff check is necessary. I think a standard cast at the beginning should be more then sufficient.  Assuming you have sufficient timing between astrology script runs, then doing a players designated max prep should cover duration and potency issues and not waste any time.  If for some reason Astrology is being activated over and over again, then I could see an issue for this.

So at the end of the day, I'd vote for:

1. leaving buff cast only at initial script start
     a) optional toggle to check every loop (if using waggle set with recast)
2. moving the buffs over to a waggle set
     a) you can use the same astrology set for multiple scripts
     b) you can take advantage of the recast timer (which could be useful for part 1)
