### ISSUE TITLE
Move Combat-Trainer//Crossing-Training Methods to more Accessible Base.lic files.

### ISSUE THREAD

**Issue by brycole** [rpherbig/dr-scripts#1639]
This is a pretty big project but I think it would help a lot with dependency scripts moving forward.  A lot of useful scripts are currently locked inside Combat-Trainer and Crossing-Trainer.  For Combat-Trainer specifically, they are coded in such a complex way (processes, class, etc) that I'm not sure how I would go about breaking them into base functions.  

What I usually end up doing is taking the methods, stripping out all the things that may not apply (such as game_state.casting) and duplicating the method in the other script.  

If I was a bit better at coding I would ideally, 1) pull method out of combat-trainer to base, 2) update combat-trainer to access base, 3) use new base method in new script.

I could be completely wrong on this so feel free to give any frank feedback!

@rcuhljr @rpherbig

**Comment by rcuhljr** [comment]
Crossing trainer is already in the works of being split completely out, and may be an easier place to start and makes more sense given the modular nature of training things.

What parts would we want to split out of combat-trainer though? Most of it's functionality only makes sense in the context of combat, and we haven't run into anything that it didn't make sense to just incorporate into combat-trainer itself instead of pulling parts out.

**Comment by intangibles** [comment]
Ahhh very nice.  Yeah I have random parts of crossing-trainer broken out for other scripts/areas that crossing-trainer doesn't support yet.  All completely hacked together that wouldn't be in any condition to post since I'm still learning all all this fits together.

For combat-trainer the initial pieces I wanted to break out were the methods related to the consume logic such as check_health and check_consume.  When I was trying to do my non-combat-trainer related heal scripts I was basically going to need to rewrite that stuff but I wasn't understanding how all the game_state stuff worked together.

Recently I was thinking that the check_buffs method would be useful broken out too. The astrology issue initially got me thinking but it could also be useful during crafting to track crafting buffs.  It could even be useful to break out/combine check_buffs and check_spells(buff script).  Then we could set up waggle sets to use for keeping up spells in combat, crafting, astrology, etc. etc.

So I guess not too many in combat-trainer!

Thank you!

**Comment by rpherbig** [comment]
I agree that we should move the individual skill buff settings into waggle/buff sets. See #1228.

**Comment by MahtraDR** [comment]
This has largely all been split today into the many commons-*.lic we have. Closing. We can treat new issues as fresh.
