### ISSUE TITLE
Summoning pathways need to respect level/ownership

### ISSUE THREAD

**Issue by rcuhljr** [rpherbig/dr-scripts#172]
[DRPrime]-DR:Andarys: "there are also some pathway focus calls in there that i cant use"

quick was the one he mentioned.

we should probably detect ones they haven't done the quest for and not use those as well.

**Comment by rpherbig** [comment]
Crossing-training trains summoning by using summon admittance, summon weapon, and pathway focus damage (see #119). The first two all WMs have, the latter is at circle 4. I considered the issue of a WM not having that pathway, but it did not seem like a problem since you get it at a low circle and nothing bad happens if you do not have that pathway (except for a bit less exp of course).

Since you mentioned pathway focus quick, my suspicion is that Andarys copied Torgro-setup.yaml. While quick does require circle 8, it's a buff_nonspell and so can be easily changed to a different pathway (or removed entirely).

**Comment by rpherbig** [comment]
I talked to Andarys in game and he was referring to pathway focus quick in combat-trainer. We were unable to reproduce what he saw. We can make a new issue if it happens again.
