### ISSUE TITLE
Red Brocket Deer area map is broken

### ISSUE THREAD

**Issue by sprode** [rpherbig/dr-scripts#1786]
Starting from 3462:
Go fence puts you in 10655, west puts you in 10656, west puts you in 10656 again.
From there, west puts you at 10657, but then climb hill puts you at 10657 again.
From there, east puts you in a labelled 10656, even though it is in the next tier.
From there, east puts you in another 10656 (total 4 rm# 10656), another east puts you at another 10657, and climbing the hill puts you at a 4th 10657.

The third tier follows the same pattern.    I wish I knew how to fix this myself but I'm still new to lich, figure it can't be that hard to fix the tags on some rooms.

Thanks in advance!

**Comment by izawwlgood** [comment]
This is an issue that stems from the way the rooms are laid out, and i think will require a more complicated fix than remapping. The rooms are ABBC-DBBE-FBBG which makes movement and mapping through the middle rooms impossible by normal mapping.

**Comment by intangibles** [comment]
I tried to fix it last week, it will take a large amount of effort to fix.  Our mapper doesn't have access to GameObj to it can't take advantage of the uniqueloot flag so the outside edge areas cannot be mapped.  The middle rooms would need to be mapped via StringProc and "peer"  which is a fair amount of work too.

I think the best and most efficient solution is adding the area to bescort.

**Comment by sprode** [comment]
If its not too much trouble, could one of you explain to a newbie what Genie does different in the mapping that makes it work for them?

**Comment by intangibles** [comment]
@sprode 

@rcuhljr has clued me that our mapper has access to the "roomobjects" field in the mapdb.  This will act similar to the uniqueloot flag that shows up on ".inspect".  This should allow mapping of the initial room, plus the transition rooms since they have unique room objects + directions.  However, these objects can sometimes be hidden if too many objects in the room.

I think our best bet for deer is to map the unique rooms with roomobjs, and then stringproc to bypass the interior rooms.  Another option is to adopt the "peer" stringproc similar to Gemstone which would give access to ALL Rooms, but require more indepth mapping.

As for Genie, it has similar problems as well.  But I believe the main difference (in common terms) is that after you map Genie, it assumes you are in the room you say you are, even if it has multiple matches.  For example... if Room 1 and 2 are duplicated, and you are in Room 3.  If "west" takes you to room 2, and room 3 is mapped to room 2 via west.  When you go west, it assumes you are in Room 2, even if it matches on room 1.  I also believe the pathing is decided before and not recalculating in mid travel/
It also has graphical mapping which makes the process a bit easier to make duplicate rooms.

There is probably some way better ways to explain this, but this is how I think it works.

Mapdb on the other hand, always checks every room you enter, and grabs the first match, and does not assume the room link you came from is the right room.  I also believe go2 checks every room as you path, so if a room bugs out while you are pathing, it will fail.

Hope this helps!

**Comment by rcuhljr** [comment]
>However, these objects can sometimes be hidden if too many objects in the room.

I implemented the dr version of room objects, and I think this wasn't a problem because the abbreviation due to too many items only happens in the room window and the room objects updates auto updates, not what you see when you first arrive in a room or look, this means for travel purposes it still works. I haven't verified in a long time but since I used these objects to map rooms in HE where people were dumping tons of junk (darkbox rooms) I think it was working correctly.

**Comment by intangibles** [comment]
@rcuhljr 

I was mostly thinking at the end of the hunt if there were too many items, it could hide the room object.  Or if people were pathing into the room someone was hunting in.

But hopefully it sounds like this won't be an issue! I'm sure we'll find out when people break it. haha.

**Comment by MahtraDR** [comment]
@rpherbig Looks like this can be closed.
