### ISSUE TITLE
add attack preferences to yaml for combat-trainer

### ISSUE THREAD

**Issue by hwoo79** [rpherbig/dr-scripts#192]
ATTACK is horrendously inefficient for combat.  SLICE, JAB, and SWING are the best damaging, balance neutral attacks for each weapon type (slicing, piercing, impact) 

Would like to see it replaced with a variable that can be defined under each weapon in gear setups. An example would be to call the variable 'affinity' and then the script could load the variable when it changes weapons.  

Example:

    gear:
    - :description: a light steel throwing axe
      :name: axe
      :is_leather: false
      :hinders_lockpicking: 
      :is_worn: false
      :swappable: false
      :affinity: slice

Just had a conversation with a combat guy, he gave me the idea.

**Comment by rpherbig** [comment]
Is `affinity` what would be output instead of `attack`?

**Comment by hwoo79** [comment]
No, SLICE, JAB, or SWING would be the output.  Affinity was just my idea for a label for the variable.

Combat guy said it's way better to spam SLICE, JAB, or SWING, depending on the weapon type, than to use ATTACK because of balance neutral and damage output.  Higher damage = higher exp per command.

**Comment by rpherbig** [comment]
Sorry, that's what I meant - outputting the value of the `affinity` setting.

**Comment by rpherbig** [comment]
The `attack` command will select an appropriate offensive verb to use. Sometimes it picks an inefficient verb, and the thought here is that by using `slice`/`jab`/`swing` instead we would be more consistently efficient.

As @rcuhljr points out, we might want to test this against enemies you can't hit reliably, since `attack` will occasionally select `bob` or the like to increase balance/positioning. Using `slice`/`jab`/`swing` would not do that. If we *need* to, that's more logic we would have to add.

From my perspective, I think I can see how this is more efficient, but I'm more convinced *how much* more efficient. Especially if we have to add `bob`/etc logic, this could be a fair bit of effort for a small gain.

**Comment by hwoo79** [comment]
https://elanthipedia.play.net/mediawiki/index.php/Category:Combat_Commands

`slice` `jab` & `swing` are all balance building commands.  So `bob` or other commands shouldn't be necessary. 

`punch` would be the equivalent, balance positive, brawling command.
