### ISSUE TITLE
Just getting started Yaml

### ISSUE THREAD

**Issue by Amala777** [rpherbig/dr-scripts#2101]
Hi!
I am just getting started currently looking to circle my trader who needs stealth and armor pretty bad.
I cannot find a sample Trader yaml. 
I tried altering Ranger one and a friend's yaml. I keep getting a validation error that my Small Edge weapon cannot be found. I did change it. Nothing I do makes the file see my weapon.

Also I need a trainer for Lang. Is that built in? I see a Crossing-trainer. 
I really need some guidance on how to make triggers. Would love for a window to shop me which rank just ranked. 

If I do create a script or download a script how do I include it in the Yaml

Def a Newbie here.

**Comment by Sarvatt** [comment]
Hey there! https://github.com/rpherbig/dr-scripts/blob/master/profiles/Cidemon-setup.yaml is a good example of a yaml for a trader, but the best advice I can give is to start small and add things as you get more comfortable with it. You may want to set your hometown to riverhaven since it is not that far from Lang yet still has crafting societies with hometown: Riverhaven added to your yaml. Even if you hunt in lang it is just a short rope bridge climb away which is handled automatically. Don't let the crossing-training name fool you, it does work in other cities but it's just too late to rename it to town-training. 

It will help if you can post your full yaml here for the small edged weapon error, after adding it highlight it all and click the <> button in the editor to make it formatted properly.

If you want to run arbitrary scripts, they go in as a before: or an after: in the hunting_info: section of your yaml, an example that runs safe-room.lic before going hunting is here https://github.com/rpherbig/dr-scripts/blob/master/profiles/Etreu-setup.yaml#L20

And welcome to lich :)

**Comment by rpherbig** [comment]
Since we don't have a sample Trader YAML, I encourage you to submit yours once you're happy with it :)

**Comment by Onbusi** [comment]
Here is my Trader's yaml:

https://pastebin.com/b4T5MGUv

I do crafting to train Trading, instead of using crossing-trainer to train it I do 1 work order for each of the disciplines before and after I go hunting.

**Comment by Amala777** [comment]
Thank you so much!! Question for you Onbusi... will that yaml train stealth. As you know we need it. Currently that and armor is all I need to circle. Trying to understand how these yaml work.

**Comment by Onbusi** [comment]
It does not train stealth. To train stealth in combat, just add this line to a yaml:

use_stealth_attacks: true

It will hide and attack from hiding until your stealth is locked

**Comment by Amala777** [comment]
thanks!
I need all the help I can get. Ive been gone a long time.

**Comment by Amala777** [comment]
having a small issue. I got the script to work but seems I do not have enough athletics to swim up to Lang from Haven. Does the script have a work around? Until then changed Hometown to Therengia and trying to just hunt

**Comment by MahtraDR** [comment]
@rpherbig Close?
