### ISSUE TITLE
error in pick

### ISSUE THREAD

**Issue by hwoo79** [rpherbig/dr-scripts#284]
I'm sure this has something to do with a setting that I'm missing in my yaml, but I've tried to search for `ensure_copper_on_hand` and `lockpick_costs` and am coming up with nothing.

    >
    --- Lich: error: comparison of Fixnum with nil failed
    	common:407:in `>='
    	common:407:in `ensure_copper_on_hand'
    --- Lich: pick has exited.

**Comment by rpherbig** [comment]
It looks like you have `lockpick_type: master` in your yaml file. `pick` uses that to refill your lockpick ring when it is done. Pick does a lookup on `@lockpick_costs` to figure out how much money it needs to have on hand. Since master is not in that hash, you got an error.

I'll add a check for unknown pick types and not refill the ring in that case.
