### ISSUE TITLE
;circlecheck broken for Thieves

### ISSUE THREAD

**Issue by ghost** [rpherbig/dr-scripts#2854]
>;circle
--- Lich: circlecheck active.
Your next level will award: 250 TDPs
You have enough 3rd Lore (Engineering) for circle 145 and need 15 (350) ranks for circle 150
You have enough 1st Weapon (Small Edged) for circle 149 and need 1 (620) ranks for circle 150
You have enough 4th Survival (Backstab) for circle 150 and need 6 (735) ranks for circle 151
You have enough 1st Survival (Perception) for circle 151 and need 7 (800) ranks for circle 152
You have enough 7th Survival (Thievery) for circle 151 and need 10 (596) ranks for circle 152
You have enough 2nd Survival (Stealth) for circle 151 and need 12 (760) ranks for circle 152
You have enough 3rd Survival (Skinning) for circle 151 and need 14 (750) ranks for circle 152
You have enough 5th Survival (Evasion) for circle 155 and need 4 (718) ranks for circle 156
You have enough 6th Survival (Locksmithing) for circle 155 and need 13 (688) ranks for circle 156
You have enough Inner Magic for circle 156 and need 3 (530) ranks for circle 157
You have enough Thievery for circle 156 and need 4 (590) ranks for circle 157
You have enough 1st Magic (Augmentation) for circle 165 and need 4 (530) ranks for circle 166
You have enough 2nd Weapon (Brawling) for circle 165 and need 4 (620) ranks for circle 166
You have enough 1st Armor (Light Armor) for circle 167 and need 2 (524) ranks for circle 168
You have enough 1st Lore (Tactics) for circle 169 and need 5 (660) ranks for circle 170
You have enough 2nd Magic (Debilitation) for circle 172 and need 8 (524) ranks for circle 173
You have enough 8th Survival (Athletics) for circle 172 and need 8 (554) ranks for circle 173
You have enough Stealth for circle 177 and need 2 (750) ranks for circle 178
You have enough Parry Ability for circle 183 and need 6 (642) ranks for circle 184
You have enough 2nd Lore (Appraisal) for circle 184 and need 8 (650) ranks for circle 185
--- Lich: circlecheck has exited.

info:
Gender: Male   Age: 23   Circle: 149

From olwydd:
What you need for circle: 150
You have enough 1st Weapon (Small Edged) for Circle 149 and need 1 (620) ranks for circle 150

**Comment by Sarvatt** [comment]
strange, i went through the circle-check code and it matches whats on https://elanthipedia.play.net/Thief#Circle_Requirements

3rd lore is 1 rank 1-30, 2 ranks 31-70, 3 ranks 71-150, 8 ranks 151-200 in it.

**Comment by asechrest** [comment]
@MahtraDR put me on this very old issue since I recently updated ;circlecheck. I believe the OP's issue is an anomaly and/or has been fixed in the 3 years since. Strangely, it lists that he has enough 3rd lore for circle **145** (when he's currently circle 149), and yet calculates the proper 3rd Lore target ranks for circle **150**. The proper readout is obviously to list what circle you have enough for, and list ranks to that circle **plus 1**. So this was a super strange error back in 2018. I haven't seen it happen recently. It could have also been a drinfomon hiccup or something.

That being said, there appears to be a discrepancy with the Thief 3rd Lore calculations in ;circlecheck vs. some of the online circle calculators.

Elanthipedia gives the Thief 3rd Lore requirements as:
![image](https://user-images.githubusercontent.com/6467969/146646693-cc828599-f2b5-4915-bc0d-cf9f59c75ed0.png)
![image](https://user-images.githubusercontent.com/6467969/146646700-4ca34435-fc87-425c-9366-5f18b2ec216e.png)

If we go with Elanthipedia's stated requirements, for a 149th circle thief per the OP, for circle 150 we'd need 350 ranks. That's: 30 ranks to reach circle 30 (1 rank per circle), plus 80 ranks to reach circle 70 (2 ranks per circle from 31-70), plus 240 ranks to reach circle 150 (3 ranks per circle from 71 to 150).

Yet Olwydd's calculator suggests we need 320:
![image](https://user-images.githubusercontent.com/6467969/146647203-503620e7-9b58-41f1-816a-38b790dbd04b.png)
![image](https://user-images.githubusercontent.com/6467969/146647216-60f336cf-4aec-4e6f-8556-fe71bd27cf90.png)

Using a test thief we tested ;circlecheck and compared against some of the online calculators.

;circlecheck:
`You have enough  Scholarship     3rd Lore      for circle  195  and need     6.05   (718)  ranks for circle   196`

[Olwydd](https://www.olwydd.org/guilds/thief/calc.php):
`You have enough 3rd Lore (Scholarship) for Circle 198 and need 1 (712) ranks for circle 199`

[ElanthiaProfiles](https://elanthiprofiles.com/circles):
`You have enough Tertiary Lore (Scholarship) for Circle 198 and need 1 (712) rank for Circle 199.`

[Matoom.github](http://matoom.github.io/calculators/thiefcalc.html):
`You have enough Tertiary Lore (Scholarship) for 198th circle, and need 1 rank for 199th.`

Those three online calculators agree with each other on 3rd Lore reqs. So I wonder if it's Elanthipedia that's wrong.

**Comment by asechrest** [comment]
The discrepancy seems to be that the online calculators calculate 3rd Lore at 2 ranks per circle from circle 71-100. Elanthipedia says it should be 3. Can anyone confirm?
