### ISSUE TITLE
Combat-Trainer: Setup file names matching script args should be an error

### ISSUE THREAD

**Issue by jandersson** [rpherbig/dr-scripts#2925]
Combat-trainer has the 'construct' argument,  but it is also possible to name your settings file `Name-construct.yaml`. A user has ran into this issue.

If I name a setup file as `Name-construct.yaml` then this file will be loaded in place of the script argument `construct` when i call `;combat-trainer construct`

In my opinion this should result in an error statement to the effect of 'argument is ambiguous, matches script argument and settings file' since we dont know if the user was trying to run the script with the construct settings file or the construct argument

**Comment by asechrest** [comment]
I'll work this issue. Interesting problem.

**Comment by asechrest** [comment]
The reported issue does not appear to be accurate OR was adjusted at some point in the past. Due to how `ArgParser` is coded, a script call will always favor matching script arguments. Any remaining unmatched arguments are thrown into `args.flex` IF the calling script passes in the proper boolean to flex the args. In other words, if a passed-in argument matches a script arg, it will _not_ go into `args.flex`, and thus not be used in a `get_settings` call.

I'll warn the user that we're favoring the script argument and to rename the settings file if they intend to flex it.

```
>;combat construct
[combat-trainer: args are: #<OpenStruct construct="construct", flex=[]>]
[combat-trainer: args.flex are: []]
[combat-trainer: In CT, args.flex are []]
[combat-trainer: args.construct is construct]
```

**Comment by jandersson** [comment]
Lets close this then, as it was opened on behalf of another user; It will be difficult to verify or follow up after 5 years. A new ticket can be opened if its persisting.

**Comment by asechrest** [comment]
> Lets close this then, as it was opened on behalf of another user; It will be difficult to validate after 5 years. A new ticket can be opened if its persisting.

No worries! I actually did make a PR based on your issue. The issue just didn't quite play out the way you specified. Granted, it was years ago. See PR: #6321

**Comment by jandersson** [comment]
fantastic! Good work :)
