### ISSUE TITLE
Almanac causing issues while completing remedy workorders

### ISSUE THREAD

**Issue by thejko** [rpherbig/dr-scripts#3248]
Have only run into this while working on remedy workorders. Almanac pauses script, stows mixing stick, unpauses, and remedy attempts to keep stirring with the stick that has been stowed. I'm not sure if it would be possible to retrieve the left hand item from where it is stowed (stick has conflicts while wearing a parry stick if it's a simple "get stick"), or if remedies/workorders in general need to be added to the list of scripts to check to prevent almanac from running.

**Comment by Tarhish** [comment]
Related -- some people are reporting that when running steal it will stow the almanac, unpause steal, and then immediately try to drop the almanac it just stowed.  It can't, of course, because it does stow the thing before unpausing the scripts it paused, but it tries and hangs for a little while because of it.  We're thinking maybe adding a no_run_scripts like sanowret has.
