### ISSUE TITLE
combat-trainer.lic: prayer badge support only works for paladins

### ISSUE THREAD

**Issue by Sarvatt** [rpherbig/dr-scripts#3296]
Clerics need to be added to it also.

**Comment by rpherbig** [comment]
Also https://github.com/rpherbig/dr-scripts/blob/7ca2f0746a39f27a6cf526d0f8afc6b456ee0a76/new-character.lic#L52

I'm surprised we never added it to `crossing-training`...

**Comment by MahtraDR** [comment]
Looking into adding this last night and today, and I think the reason it wasn't added for clerics is two-fold. The main reason is it is a very small devotion boost, and it's on an 80 minute timer. We basically max out devotion with theurgy, then go into combat, and maintain it with prayer mats during combat. I don't want to add in code we end up having to maintain for marginal benefit. Closing this, since it's 3 years old, and has no traction today. Should it come up again, we can review that as a fresh request.
