### ISSUE TITLE
combat-trainer doesn't always stow after firing

### ISSUE THREAD

**Issue by proctophage** [rpherbig/dr-scripts#3300]
https://pastebin.com/pQBEBCgt

see pastebin
I sometimes run out of ammo (since it always loads from container) even with 11 shards on me
it's not uncommon after just a 60 minute hunt for 9-11 shards to be at my feet by the end

**Comment by Sarvatt** [comment]
Do you have more of a log you could share? Do you notice any patterns? I noticed it was at missle range there and engaged and started doing aim_fillers instead of stow my shard

**Comment by Sarvatt** [comment]
I thought it was a case problem with You fire, but I was stupid and didn't /i on rubular testing it so it wasn't that.

**Comment by proctophage** [comment]
https://pastebin.com/fw9xNvu9
Sure, here's another one where it didn't stow.
Looks like when things die or it switches weapons it's not stowing the ammo properly.

**Comment by RyanEOD** [comment]
@Sarvatt  - I'm still having a problem with my sphere getting stowed, then combat-trainer ends and go2 kicks off and I don't move because the sphere is still sitting at my feet. Here are two examples of message:

Stowed:

You slip quietly from your hiding place, convinced that you successfully poached your target.
< You poach a matte indurium sphere at an Adan'f blood warrior.  An Adan'f blood warrior completely fails to block with its oval shield.  
The sphere lands a massive strike (11/23) that rips the top layer of skin from the warrior's chest and exposes underlying muscle, severely stunning it.
The matte indurium sphere falls to the ground!
[Roundtime 1 sec.]

Did not stow;

< You poach a matte indurium sphere at an Adan'f blood warrior.  An Adan'f blood warrior badly fails to block with a battered oval shield.  
The sphere lands a very heavy hit (8/23) that temporarily knocks away the warrior's breath with a light blow to the chest.
The matte indurium sphere falls to the ground!
[You're incredibly balanced and in dominating position.]
[Roundtime 1 sec.]

Here is my paste bin - https://pastebin.com/gyUx4Nuj

**Comment by Tarhish** [comment]
Okay, I spent a while looking at this on lnet, and the full log helps.  I see why this happened.  It stows when it sees ```'/you (fire|poach|snipe) an? (?:.*\s)?(arrow|bolt|shard|rock|sphere|clump|coral|fist|holder|lump|patella|pellet|pulzone|quadrello|quill|stone|stopper|verretto) at/i'

**Comment by Tarhish** [comment]
case bput(command, 'isn\'t loaded', 'There is nothing', 'But your', /you (fire|poach|snipe) an? (?:.*\s)?(arrow|bolt|shard|rock|sphere|clump|coral|fist|holder|lump|patella|pellet|pulzone|quadrello|quill|stone|stopper|verretto) at/i, 'I could not find', 'with no effect and falls to the ground', 'Face what', 'How can you (poach|snipe)', 'your moving to fire went unobserved', 'notices your attempt to remain hidden', 'you don\'t feel like fighting right now', 'That weapon must be in your right hand to fire')
