### ISSUE TITLE
wishlist: allow cast_only_to_train to release (offensive) cyclics

### ISSUE THREAD

**Issue by thejko** [rpherbig/dr-scripts#3414]
This would be great when training with spells like USOL, as well as any cyclic that is simply being cast to train a certain skill. Currently, cast_only_to_train will cast a cyclic when it needs training, but it won't release cyclics once they reach the specified mindstate.

This could also help mana usage when running a cyclic in combat by releasing the cyclic when locked, freeing up additional mana for training more skills.

**Comment by MahtraDR** [comment]
It's not exactly the same thing, but in the mean time we've got `release_cyclic_on_low_mana` and `release_cyclic_threshold` which accomplish the stated goal of dealing with mana management from cyclics. Given how old this issue is, I'm closing it out.

I'd be happy to look at this issue as fresh whenif it comes up again.
