### ISSUE TITLE
Add validate checks for spell merge failing

### ISSUE THREAD

**Issue by jandersson** [rpherbig/dr-scripts#3466]
;validate should run a check on the users listed spell sets that are merged with base-spells. If anything fails, issue a warning.

**Comment by jandersson** [comment]
Add an artificial field like `is_for_test: yes` to all spell data loaded into a test, do the merge, then check if that field exists in all the users merged data

**Comment by Tarhish** [comment]
That's a great idea.

So I put in  def assert_that_spells_are_in_base_spells.  Right now it just checks names, but many spell categories don't really include names, just abbrevs.

When I first pushed that change it also compared abbrevs, but it turned out just about EVERYONE was getting validate errors because nobody's abbrevs matched base-spells, so I reverted that.  A case-insensitive check would make that a lot less problematic.

**Comment by jandersson** [comment]
I would say its fair to make it a warning instead of an error. Dont think we should worry about each field matching, more so that the merge worked

**Comment by jandersson** [comment]
I missed that that check existed. I think it might be good to start thinking about how to make validate more easily searchable. I dont know if that means breaking it up into separate files or what

**Comment by MahtraDR** [comment]
Closing as wontfix.
