### ISSUE TITLE
Workorders and/or Crossing-Trainer Crafting Routine Adjustment

### ISSUE THREAD

**Issue by izawwlgood** [rpherbig/dr-scripts#3800]
I spend a decent amount of time waiting for my tools to be repaired. I think a better approach would be 'tools are turned in for repair, and then the next task is handled. When it's time to do another craft, it's checked if there are tools for that craft, and if there aren't, it's checked if there are repair tickets. You can LOOK AT TICKET to get info about which craft it applies to - 
`Written at the bottom you see Forging Society, West Hall, Ilithi.`
At the beginning of a craft, if the tools are with the clerk, and tickets are in a container, the tickets are handed in for the tools, and the craft is started. 
I think this will save a couple of minutes per craft, as you aren't sitting there idly waiting for the tools to be repaired.

**Comment by Kaesken** [comment]
Honestly was going to suggest something similar as well.  Especially since mine kept trying to repair my mixing stick for some reason and they won't fix that then it busts my entire script.  Then it moves on, with my mortar and pestle still being repaired and by the time it returns to do more alchemy, it can't because now it cannot find the mortar and pestle.

**Comment by MahtraDR** [comment]
Closing as something we aren't likely to get to. It's been sitting for 4 years, no sense leaving it open longer.
