### ISSUE TITLE
smith/forge threw away tools

### ISSUE THREAD

**Issue by Akhorishaan** [rpherbig/dr-scripts#3847]
https://pastebin.com/vaevTqQR
Ran into an issue where if the smith/forge scripts encountered an ingot with not enough material for the crafting project, it would throw your tools in a waste bucket.  This can happen sometimes if you have a few small ingots on you for custom crafting projects and they happen to be in an earlier container in your inventory than your stow container, and stow custom ingot isn't set.

Quick rundown of what happened:
Smith script started, bought a bronze ingot, put the ingot in my backpack, then went to an anvil.  Then it studied the book, put an ingot FROM MY SATCHEL on the anvil, tried to do the first pound and found out there wasn't enough material, exited the forge script, went to the forging supplies room, tried to "get my bronze ingot" again, had a no-match error, then throw my tools in the nearest waste bucket.

I had a couple small (1-3 volumes) ingots in my satchel (which is my crafting_container) for some custom projects I was doing, which made it grab one of those and go into a subroutine to get another ingot, but the hands were full since  the forge script didn't put the tools away after finding out there wasn't enough material to work with.

**Comment by jayRyan24** [comment]
This looks like a definite issue within forge.lic. The first thing to be done is that the scripts should handle errors by putting the gear away first, and not just exit. I think at this stage and to get this error, it's always at the beginning, so there needs to be a stow_item for each of the starting items, but this is definitely a bug that should be fixed. Another issue is that craft.lic should handle thing better as well, and instead of just disposing of the items in hand, it should handle them as possible items that belong to the player. 

I think the biggest issue, especially one found in Dependency, is that there's a mindset that it should be done a certain way and if it isn't, then it's being done wrong. I'm not sure how others haven't run into this issue all the time before, including myself, especially the big crafter/Traders. Possibly it's because they use deed packets, and my extra ingots were always kept inside containers in other containers, but regardless, this is an issue.

This is probably where the item cleanup should go for forge. Something big went wrong, but it can at least handle putting the crafting items away.
```
    when 'You need a larger volume of metal'
      echo '***You need a larger ingot to forge this item.***'
      magic_cleanup
      exit
```

**Comment by jayRyan24** [comment]
Usually the first item in the inv list to get is the one last touched. So, this thing should make the ingot, cut it, and then use it. Did it do anything else between the time it cut it, or did you do anything with inventory before that, to reorder?

**Comment by jayRyan24** [comment]
Looks like pound is always hammer and tongs, nm.

**Comment by jayRyan24** [comment]
Thanks for making this issue. I posted the fix PR just now.

**Comment by Akhorishaan** [comment]
Looks like when you throw a generic "get my ingot" out there, it will go through your inventory from head to toe, and pull an ingot out of the first container that has an ingot, so if you commonly store your ingots in a container (in this case hide satchel) that comes before your stow container (in this case backpack) then it will grab one of the ingots from the satchel before it even considers the ingot that was stowed into the backpack, because the satchel shows up sooner in the inventory list:

You are wearing a midnight black cowl, a brilliant incarnadine uaro's'sugi of lightweight firesilk, a silver kyanite gwethdesuan, a chubby cassava root affixed with googly eyes, a billowing dragonfire brocade greatcloak roiling like a furious firestorm, **a dusky-blue basilisk hide satchel decorated with ur hhrki'izh claws along the flap, an ebony leather backpack embroidered along the flap with a crimson dragon**, some voluminous black robes with outturned cuffs, some midnight black leathers, a coiled silver armlet shaped like a snake studded with cambrinth scales, a midnight black shield, a snake charm, a sanowret crystal, an etched steel parry stick with black leather straps, some midnight black gloves, a platinum wedding band coiled like a sleeping dragon, some polished thin-edged zills with silvered esoteric filigree, and a dark adderwood tailband edged with sanguine dragon's blood crystal.
