### ISSUE TITLE
Combat-trainer hangs when RT prevents armor swapping

### ISSUE THREAD

**Issue by DRWafflesworth** [rpherbig/dr-scripts#3931]
[combat-trainer]>stow my shard
You pick up the shard lying at your feet.
You put your shard in your thigh quiver.
[combat-trainer]>remove my chain.greaves
You remove some silversteel chain greaves with tiny cabochon star diopsides running around the edges from your legs.
[combat-trainer]>stow my chain.greaves
You put your greaves in your warrior's duffel.
[combat-trainer]>get my scale.greaves
You get some lumium scale greaves from inside your warrior's duffel.
[combat-trainer]>wear my scale.greaves
The clumps of dirt stinging your eyes cause your vision to go spotty and black!
Roundtime: 4 sec.
...wait 4 seconds.
[combat-trainer]>sort auto head
Your inventory is now arranged in head-to-toe order.
[combat-trainer]>load
You reach into your quiver to load the lirisan pelletbow with a quartzite stone shard.
Roundtime 6 sec.
[combat-trainer]>aim
...wait 1 seconds.
[combat-trainer]>aim
You begin to target a lava drake.
[combat-trainer]>wield my nightstick
You need to have a free hand to draw your diamondwood nightstick.
...
[combat-trainer: *** No match was found after 15 seconds, dumping info]

**Comment by Tarhish** [comment]
Good catch.  In equipmanager:

```
    when item.short_regex
      fput("wear my #{item.short_name}")
      waitrt?
      return true
```
This fput is the problem.  It failed due to that mud in the eye but thought it resolved correctly because fput's aren't as robust and it thought that 'mud in the eyes' message was a successful resolution.  I'm not sure what the best way to solve this at the moment is, since there are probably a lot of messages involved in converting it to a bput.
