### ISSUE TITLE
stuck in aim/load loop

### ISSUE THREAD

**Issue by GreyhallowDR** [rpherbig/dr-scripts#3936]
I have consistently experienced this but cannot find a fix in yaml. Is there a change that can be made to combat-trainer to get out of or prevent this?

The last time the bow is fired in the log was me sending it manually to see if it would shake loose from the loop. It went right back into it after loading again. I think it is missing the "fully targeted" trigger somehow. 

LOG: https://pastebin.com/nFVG4Uht

**Comment by Sarvatt** [comment]
we should probably make validate spit out an error if the weapon is swappable in aiming trainables like here

**Comment by GreyhallowDR** [comment]
ok, so a swappable aiming trainable is a no-go?

**Comment by Tarhish** [comment]
Yeah, it looks like what's happening is the instant you pull out a swappable weapon that's in 'handheld mode' the aiming stops, since you can't aim a bow and hold a melee weapon offhand.  combat-trainer has a check to prevent you from doing that, but as far as it's concerned your swappable is a thrown weapon, not a melee one, so it doesn't notice.  I don't think there's a real way to make it work aside from forbidding it entirely.

**Comment by MahtraDR** [comment]
@rpherbig Can close this. Known issue, and swappables aren't allowed as offhand anything (because they don't work there)

**Comment by rpherbig** [comment]
#5397 should take care of this
