### ISSUE TITLE
Hib forge area

### ISSUE THREAD

**Issue by Kaesken** [rpherbig/dr-scripts#3944]
I did a boo-boo guys.  I'm sorry.  Can someone help?
Someone said that the Hib forge wasn't mapped so I went up to map the area, not realizing it was originally mapped already.  I didn't know it was going to give it a new set of numbers (I was hoping just the room title would change if it was previously mapped).

Apparently instead of it being "Forging Society" it's recently been changed to "Hibarnhvidar Forging Society".

Also, would the person who fixes my fuck up be able to explain how to edit titles rather than re-map the area?  I honestly didn't know it was going to remap the section.  Again, my apologies.

**Comment by Tarhish** [comment]
I can definitely take a look later.  There's no, uhh, automap way to fix titles because normally they don't change.  When I'm adjusting a room title, I would find the first connecting room that's still mapped, do an lfr to find out what number the broken room is _supposed_ to be, verify it's correct and not a fluke, then manually change the title.

The command would look like `;e Room[361].title=["[[Riverhaven, River Road West]]"]`

Then I'd walk into that room and verify that the map figured it out, then move on from there.  With crafting societies or hunting zones it's a good idea to make sure that the numbers in, say, base-crafting for Hibarnhvidar forging seem to match up to the rooms you've mapped, and that you didn't miss any, since some are mazelike.

**Comment by Tarhish** [comment]
I've done this like a dozen times now so I'm starting to get the hang of it.  I stopped by the Hib forge and removed the new rooms, then adjusted the old ones.  I can navigate in and around there now, so here's hoping I didn't miss anything.

**Comment by Kaesken** [comment]
Ok, thank you so much, @Tarhish .  I'm still learning, lol.  I appreciate it!
Yeah I wasn't thinking about that when I remapped the areas then when my friend who told me it wasn't mapped said that workorders weren't working, my first thought was "Oh, f**k".
I use Genie maps to guide me while I map unmapped areas, so I rarely miss hidden rooms.  (Hell I know of some secret rooms lol - lichers don't like it when I hide cause if they don't have access to genie maps they don't know where I am.  XD)

**Comment by Tarhish** [comment]
I've done the same things learning to map, though at the start I was only fixing problems I knew I needed for myself, so I could pretty quickly tell when my own actions weren't working.
