### ISSUE TITLE
Caravan not in correct place when giving new contract to clerk

### ISSUE THREAD

**Issue by GreyhallowDR** [rpherbig/dr-scripts#3959]
There is a high chance that each time town_business sub runs that your caravan will follow you away from the room it was left in. This results in the caravan not being in the right place to get loaded when getting a new contract. 

I was able to resolve this by telling the caravan to wait at the beginning of town_business.

Anytime the script leaves the caravan it should be told to wait. It often doesn't follow when you walk away, but actually "follows" on your way back when you're 1 room away from returning to it. 

  def town_business # run every time it delivers/picks up a contract from Crossing/another hub. Replenishes resources and stocks coins
    return if time_to_room(Room.current.id, find_closest_id('trader_outpost')) > 5.0
    room = Room.current.id
    **command_caravan?('wait')**
    deposit_coins(@caravan_coins_on_hand)
    withdraw_coins(@caravan_coins_on_hand)
    check_hunting
    check_forging

**Comment by Tarhish** [comment]
Yep, you're right.  Due to a fluke of typeahead and fortune I zip out of the next room before it has a chance, so I never saw this.

I added a wait to another section before entering town_business that prevented this in certain places, but it wasn't before each call, and it would be better off in there, at the beginning of every entrance to town_business
