### ISSUE TITLE
Glyph of Warding Support - Combat Trainer

### ISSUE THREAD

**Issue by wscherer420** [rpherbig/dr-scripts#4077]
Glyph of Warding has been updated with some new features. One of them is a favor cost reduction upon death when cast on oneself.  It would be great if at the beginning of combat-trainer, for paladins, a glyph of warding would be traced upon ourselves.

**Comment by MahtraDR** [comment]
This would be a neat first issue for someone. Just copy the code for mana glyphs, and adjust for Warding.

**Comment by MahtraDR** [comment]
Hard out. So even the favor cost reduction is gone?

**Comment by Sanzia** [comment]
https://elanthipedia.play.net/Post:Let%27s_Do_the_Glyph_of_Warding_Again_-_12/08/2020_-_21:32  So not really but not really worth the soul hit to maintain that.  Especially in combat using SMITE.  But how the GM explained it, DEPART COINS is now treated as DEPART FULL if you have Glyph of Warding on. The price remains at 2 favors after discount and you retain your items. This is an edge-case nerf for Paladins that were DEPART COINS-ing with the Glyph for a two-favor reduction of the cost of services rather than one.

**Comment by MahtraDR** [comment]
How lame. Cool you researched and learned something from it though. Shall we close this issue then?

**Comment by Sanzia** [comment]
That would be my recommendation.  This research did show it would be great to setup a Lich trigger that would send the command 'glyph ward {Character Name}' when you see the line, '{Character Name} is aiming at you.'  This would reduce their accuracy significantly.  That's my next project and the only real benefit left in GOW.  That's going to be next project to see if I can get that working.

**Comment by MahtraDR** [comment]
@Sanzia Thank you for the research you put into this. I'm closing this issue now.
