### ISSUE TITLE
Afk stopping Go2?

### ISSUE THREAD

**Issue by khrispyb** [rpherbig/dr-scripts#4094]
This may just be a setup issue on my end, but I had this issue occur where AFK stopped go2 which then resulted in my afters being executed in my hunting grounds aka death:

[hunting-buddy]>release SLS
Release what?
[Check RELEASE HELP for more information.]
>
| ***STATUS*** EXECUTE go2 812
--- Lich: go2 active.
--- Lich: 'textsubs' has been stopped by go2.
[go2: ETA: 0:00:34 (75 rooms to move through)]
[go2]>down
You feel fully rested.
>
You notice a drake-fang arrow at your feet, and do not wish to leave it behind.
>
[afk]>stow feet
>
You pick up the arrow lying at your feet.
You put your arrow in your belt quiver.
>
[afk]>stow feet
Stow what?  Type 'STOW HELP' for details.
>
--- Lich: 'go2' has been stopped by afk.
--- Lich: go2 has exited.
| ***STATUS*** EXECUTE lockbox
--- Lich: lockbox active.
[lockbox]>get my training box
>

**Comment by Tarhish** [comment]
This isn't really a setup problem -- ever since Simu changed how loading and ammo at your feet works there's still the occasional bug we're finding where you get stuck.  go2 can't quite handle it at the moment.  Until all the problems get ironed out, use ;get2 in your afters instead of ;go2.  get2 is just go2 except it will try again if afk gets stuck with something at your feet.

**Comment by khrispyb** [comment]
very good to know, thank you.
