### ISSUE TITLE
Analyze Accuracy error, did not recognize string response

### ISSUE THREAD

**Issue by Tyrranny** [rpherbig/dr-scripts#4313]
The below command errors out, the script does not recognize the response.

[combat-trainer]>analyze accuracy
With a keen eye you study the battlefield and try to discern what weaknesses may be exploited.
Your lack of expertise prevents you from maneuvering in that manner.

[combat-trainer: message: Your lack of expertise prevents you from maneuvering in that manner.]
[combat-trainer: message: With a keen eye you study the battlefield and try to discern what weaknesses may be exploited.]
[combat-trainer: checked against [/cannot repeat/i, /Analyze what\?/i, /by landing an? .*/i, /You need to hold/i, /You must be closer/i, /You fail to find any/i]]
[combat-trainer: for command analyze accuracy]

**Comment by Tyrranny** [comment]
I have 50 expertise which is supposed to be the requirement according to elanthia.

**Comment by jayRyan24** [comment]
Not sure if this is an issue we need to fix for. This is basically an error on their part or an error within the epedia. I would just turn off analyzing until a successful test manually yields success. Otherwise, people would be doing this without really knowing it's failing. This type of warning let's you know "something is wrong" and not "working as expected". Know what I mean?

**Comment by MahtraDR** [comment]
@rpherbig close? No meat to dig into here.

**Comment by Tyrranny** [comment]
Yes, I never traced a root cause but moved my download directory to point at my data drive and it let me click download anyway. Had all security off that I know of and I'm a data center engineer. I suspect it was something I installed after rsl, it had been working until then.

Thanks for your hard work!

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
