### ISSUE TITLE
Pick.lic gem issue - "fill <gem container> with <boxname> isn't checking for the right response

### ISSUE THREAD

**Issue by brewguyver** [rpherbig/dr-scripts#4349]
I recently started seeing the following problems

1. When the "Fill my gem pouch with my <boxname>" command is used, line 273 doesn't appear to be checking for "You fill your ...", causing a 15 second delay on every box. I tested this locally by adding 'You fill your', to current line 273 (the one that starts with bput("fill my #{@settings.gem_pouch_adjective} pouch with my #{box}",)
2. The fill command has some issues - it ignores "store" settings in game, so it may attempt to fill a pouch that isn't being worn. This is an issue for characters that have multiple gem pouches with different descriptions. For example i was wearing "a red gem pouch" and had "a dark gem pouch" in my filled pouch container. The "Fill my gem pouch with my <boxname>" was trying to fill the stored pouch and not the worn pouch. I fixed this temporarily by wearing different pouches until the one I was wearing matched the "fill my gem pouch" command. Note - this seems to be a problem with gem pouch descriptions and identification in DR and not something introduced by lich.

**Comment by Hiinky** [comment]
Thanks for the feedback.

1)  Updated.  I believe the difference here is an open vs tied gem pouch so new match added.

2) It will always use the `gem_pouch_adjective` set in your yaml.  I recommend never ever using `gem` as that adjective for this reason.  It is a known bug with simu randomly changing color adjectives asking for a gem pouch instead of a red pouch.  having random color pouches won't work well anywhere with lich.
actual code never uses the word gem: `"fill my #{@settings.gem_pouch_adjective} pouch with my #{box}"`

If you hate it or its causing you issues, it can be turned off:
`fill_pouch_with_box:`
true = always use fill no matter what
false = never ever
blank = depends on if loot_special is empty - most user friendly

**Comment by Hiinky** [comment]
Addressed:  https://github.com/rpherbig/dr-scripts/pull/4350

Can be closed.
