### ISSUE TITLE
combat-trainer ranged weapons

### ISSUE THREAD

**Issue by Kaesken** [rpherbig/dr-scripts#4351]
It doesn't appear it handles when you run out of arrows/bolts.  It keeps going in a "load" loop.

Here's the messaging when you don't have any bolts:
You don't have the proper ammunition readily available for your light crossbow.

**Comment by Hiinky** [comment]
Someone else might have a better answer but there's not really any way to handle this easily.  You could leave hunting to go get ammo but if you have no restock, it will loop endlessly.   If you just skip the weapon with no ammo, it could stop training for god-knows-how long  because it is again dependent on ;restock or human interaction.

**Comment by KatoakDR** [comment]
This issue has been resolved by:
* https://github.com/rpherbig/dr-scripts/pull/4690
* https://github.com/rpherbig/dr-scripts/pull/4682

Thank you

@rpherbig this may be closed
