### ISSUE TITLE
Using enchant for the first time and it's looking for a finished part rather than creating it

### ISSUE THREAD

**Issue by Angel-DR** [rpherbig/dr-scripts#4437]
Genie user

,enchant 2 cambrinth retuner

[enchant]>get my retuner from my enchanter's satchel

Why is it assuming it exisits already?  Does this script not create any items, but rather only enchant them after they were created?  I am new to the entire crafting system.  Thank you in advance.

**Comment by vtcifer** [comment]
What does `,enchant help` say?

**Comment by Angel-DR** [comment]
> ,enchant help

--- Lich: enchant active.

--- Lich: equipmanager active.

--- Lich: equipmanager has exited.

>
  enchant <chapter> <recipe name> <noun>

   chapter      Chapter containing the item.

   recipe name  Name of the recipe, wrap in double quotes if this is
multiple words.

   noun

--- Lich: enchant has exited.

So I run it by the directions but it expects the tuner to be made,  It's
really odd.

 ,enchant 2 cambrinth retuner

[enchant]>get my artificing book
You get a book of master artificing instructions from inside your
enchanter's satchel.

You turn your book to chapter 2, entitled "Utility and Fluff Artificing".

[enchant]>turn my book to page 3
You turn your book to page 3, instructions for crafting a cambrinth retuner.
>
[enchant]>study my artificing book
You scan the retuner instructions with a glance and completely understand
all facets of the design.
You now feel ready to begin the crafting process.

[enchant]>get my silver brazier
You get a small silversteel brazier scattered with glittering starstones
from inside your enchanter's satchel.
>
[enchant]>get my retuner from my crafter's bag
What were you referring to?

**Comment by vtcifer** [comment]
>enchant \<chapter\> **\<recipe name\>** _\<noun\>_
>chapter      Chapter containing the item.
>recipe name  Name of the recipe, **wrap in double quotes if this is
multiple words.**
>_noun_

**Comment by mtruitt** [comment]
It works fine, in this case it is rod.

Noun refers to the item is ENDS as and you work with.

A list of ingredients is provided:

   (1) A finished stone, bone or wood rod.
   (1) mana fount
   (1) primary sigil (congruence)

**Comment by Angel-DR** [comment]
I'm sorry, it does not work fine.  It is trying to GET tuner, not create
it.

Please tell me the exact syntax you using for it to work.

**Comment by Hiinky** [comment]
``` 
;enchant <chapter> <recipe name> <noun>
   chapter      Chapter containing the item.
   recipe name  Name of the recipe, wrap in double quotes if this is multiple words.
   noun
```

In your case you want to make a tuner from chapter 2
The recipe would be "cambrinth retuner"  in double quotes specifically.
The finished item is not actually called a cambrinth tuner.  It's the noun of your (1) A finished stone, bone or wood rod.

`;enchant 2 "cambrinth retuner" rod`  is correct usage.

The last one I made was from a maple rod I carved myself so the final product was an rather inconspicuous `maple rod` I had to be careful to keep separate from anything else.

The script is working as expected in this case since "cambrinth retuner" was not in quotes it was accepting retuner as the item to use while crafting.  Please close the issue once you've had a chance to review.

**Comment by MahtraDR** [comment]
@rpherbig this can be closed.
