### ISSUE TITLE
combat-trainer stalls after action count/skill check/stance change

### ISSUE THREAD

**Issue by debidjang** [rpherbig/dr-scripts#4505]
Been running it for a long while on other characters, but for some reason on a cleric combat-trainer often stalls soon after startup after drawing the first weapon:

```[combat-trainer: action count: 0 vs 15]

[combat-trainer: skill exp: 0 vs -1]

[combat-trainer: new skill needed for training]

[combat-trainer: checking weapons as nil!=Light Thrown]

[combat-trainer]>wield my shoe

> 
> 
You draw out your leather shoe from the hip pouch, gripping it firmly in your right hand.
> 
[combat-trainer]>stance set 98 100 0
> 
Setting your Evasion stance to 98%, your Parry stance to 100%, and your Shield stance to 0%.  You have 0 stance points left.
```
Sometimes it will go through combat for awhile only to stall at a similar spot after looping through for 5-10 minutes.  Tinkered with the YAML endlessly, but can't figure out what could be wrong.  No error messages or anything, it just stops.  I feel like I'm missing something silly, but can't figure it out.  Any input would be greatly appreciated.  

YAML:  https://pastebin.com/N9iyvsJn

**Comment by Hiinky** [comment]
Could you send more log?  From the time combat starts to the time it stalls?  And when it stalls does it do nothing at all or just not weapon things?

**Comment by Hiinky** [comment]
My two guesses:
Running somewhat blind is an interference between  offhand_thrown: and attack overrides.  Almost no one uses offhand_thrown anymore with aiming_trainables but I see you don't have an aiming type weapon so I see why you want to use it.  For the sake of testing I would try turning `offhand_thrown: false` and see what happens.

Second Guess:
Priority weapon syntax is a bit off so that may also be causing some funny results.  Replace your current section with this and see what happens.
```
priority_weapons:
  - Large Blunt
  - Light Thrown
  - Heavy Thrown
```

**Comment by debidjang** [comment]
Thanks for the suggestions.  I tried them, but am getting the same result.  

Here's more log with the suggested changes from startup to stall.  This is the typical place where it stalls...right at the beginning.  I have no idea why it loops through for a bit sometimes.  

LOG: https://pastebin.com/0VKmgDMe
YAML used: https://pastebin.com/b5FjwAYX

**Comment by vtcifer** [comment]
Based on the larger log, and yaml, I suspect what is going on is it's hanging in SpellProcess.execute, specifically if you have less than full mana it will pause waiting for full mana to infuse.

'Stack trace' is follows:

$COMBAT_TRAINER.start_combat steps through each of the class execute methods in this order:
setup
spell
pet
ability
loot
manipulate
trainer
attack

You can see it gets through setup, because that's what opens the containers, wields your checks weapon to train, wields it and sets stance.  (which is the end of SetupProcess.execute).  

The next thing is Spell.Process.execute and one of the very first things it does is  check_osrel(game_state) which attempts to infuse your orb:

infuse_om(!@osrel_no_harness, @osrel_amount)

Which is called from module DRCA

```ruby
def infuse_om(harness, amount)
    return unless DRSpells.active_spells['Osrel Meraud'] && DRSpells.active_spells['Osrel Meraud'] < 90
    return unless amount

    success = ['having reached its full capacity', 'a sense of fullness', 'Something in the area is interfering with your attempt to harness']
    failure = ['as if it hungers for more', 'Your infusion fails completely', 'You don\'t have enough harnessed mana to infuse that much', 'You have no harnessed']

    loop do
      pause 5 while mana <= amount
      harness_mana([amount]) if harness
      break if success.include?(DRC.bput("infuse om #{amount}", success, failure))
      pause 0.5
      waitrt?
    end
  end
```

The problem line is ` pause 5 while mana <= amount`

The issue is mana, is likely a % number, and amount is a # of streams.  Because you are infusing 100 `osrel_amount: 100`, it waits until you have full mana. This comparison could likely use some tweaking.  What it should be changed to I haven't thought about tbh.

In the interim I'd lower your osrel_amount.

**Comment by Hiinky** [comment]
Can confirm 100% this is the issue.  Ran into it on my cleric a while back and didn't remember seeing it until VTC picked out that line.  99 works and 100 breaks the universe.  Realistically though even a max level cleric can use 50 just fine so lowering the osrel_amount: should fix things.

**Comment by debidjang** [comment]
Amazing, that fixed it!  Thanks so much to you both.
