### ISSUE TITLE
Prepare to move this repo to the dragon-realms organization

### ISSUE THREAD

**Issue by rpherbig** [rpherbig/dr-scripts#4888]
I'm thinking of this process:

1. Update `dependency` to handle a fallback URL (see https://github.com/rpherbig/dr-scripts/blob/6c4f93716cbd1047f51fef1b542b91f1f01b92e0/dependency.lic#L161-L162) - the primary would be this URL, the fallback would be https://github.com/dragon-realms/dr-scripts/
2. Wait a while for the change to propagate (two weeks?)
3. Move the repo
4. Update the 'new' repo to no longer check the `rpherbig` URL

Based on the GitHub docs (https://docs.github.com/en/github/administering-a-repository/transferring-a-repository)

**Comment by KatoakDR** [comment]
Woo hoo! Moving to an organization will unlock a lot more capabilities for maintaining this open source project.

One of which I'm excited about is ability to grant folks [triage access](https://docs.github.com/en/organizations/managing-access-to-your-organizations-repositories/repository-permission-levels-for-an-organization) so that they can manage issues and pull requests without write access.

**Comment by rpherbig** [comment]
From @BinuDR :
> I would suggest that when we move the repo over there that we add in a samples folder into profiles and move all of the sample yamls into that so that the profiles folder can be only for base, base-empty, and all personal yamls

I like the idea

**Comment by MahtraDR** [comment]
> From @BinuDR :
> 
> > I would suggest that when we move the repo over there that we add in a samples folder into profiles and move all of the sample yamls into that so that the profiles folder can be only for base, base-empty, and all personal yamls
> 
> I like it - note: it doesn't have to be part of the first PR, I just needed a place to record the idea

Any objection to the Samples folder now? I like this idea, and it's easy.

**Comment by BinuDR** [comment]
> > From @BinuDR :
> > > I would suggest that when we move the repo over there that we add in a samples folder into profiles and move all of the sample yamls into that so that the profiles folder can be only for base, base-empty, and all personal yamls
> > 
> > 
> > I like it - note: it doesn't have to be part of the first PR, I just needed a place to record the idea
> 
> Any objection to the Samples folder now? I like this idea, and it's easy.

No objections from me.

I had another idea too.  Maybe we should have subfolders for each guild so it's easier for everyone to find a yaml for the guild they're looking for.

**Comment by rpherbig** [comment]
Works for me

**Comment by MahtraDR** [comment]
Didn't get to this today, but might tomorrow. One thing came up. Speaking with a new-to-lich person, they commented that some of the yamls are really out of date. Do we want/mind some basic triaging of the yamls we have?

In my mind, we don't need lots, but we need good examples for people. Opinions?

**Comment by MahtraDR** [comment]
@rpherbig @BinuDR Have a look at https://github.com/MahtraDR/dr-scripts/tree/clean_profile_dirs_sort_samples_into_guild_folders please? If it looks ok, I'll submit as a PR.

**Comment by asechrest** [comment]
I like that file structure.

Also in my opinion, even some of the `sample*.yaml` could use significant updates and more robust commenting. Yaml help is one of the more frequent things we get asked for in Discord. And for new folks it is fairly clear there is significant confusion centering around a list things:

- How do I start? (Answer: _not_ by copying an entire advanced yaml with most of the settings)
- What do the settings do?
- What scripts are they for?
- Why am I getting an error (likely: syntax - spacing/indentation)
- How can I check my syntax?
- How do I get help?

I think it would be neat if all sample yamls came with a defined and consistent header with some basic info and links. And if each setting or section came with a defined style of comments that gave some information on that setting, including what it does, what common scripts use it, maybe whether it's a basic or advanced setting (so that a new user could understand whether this might be critical to get a set of basic scripts running or not).

I can commit to working on the Ranger sample.

**Comment by rcuhljr** [comment]
Since I like making work for people, the dream might be doing a set of sample yamls for like 5 different circles for a class, and in each one comment specifically the things that changed from the previous one and why. So level one wm file casts fireshard, hunts rats, and that's it. level  5 one might have two spells, one buff, and locksmithing since it starts hunting goblins whatever, and then a higher one level one starts using cambrinth, and spell combat, etc. etc. Might just be my software brain though that likes looking at changes in files >.>

**Comment by MahtraDR** [comment]
> Since I like making work for people, the dream might be doing a set of sample yamls for like 5 different circles for a class, and in each one comment specifically the things that changed from the previous one and why. So level one wm file casts fireshard, hunts rats, and that's it. level 5 one might have two spells, one buff, and locksmithing since it starts hunting goblins whatever, and then a higher one level one starts using cambrinth, and spell combat, etc. etc. Might just be my software brain though that likes looking at changes in files >.>

@Gildaren and I discussed this. That's the vision on our side too. Level 1, level 50, level 100. Beyond that others will have to chime in since that's where mine top out at the moment. :D

**Comment by rpherbig** [comment]
I'm not sure if it would help, but I checked in all of my characters' YAMLs pretty regularly. You should be able to go through their git history and pull out some versions at notable circles. Maybe they're too old and/or it would be too much effort, though.

**Comment by MahtraDR** [comment]
Level 1 data will be easy, we can start f2p character for each. From there, we can look at yaml histories and fish for level-appropriate yamls per class. I've recently done level 1-~80 on bard/cleric and have those histories.  Our most underdocumented class is trader if you have one of those with history that might help a lot.

**Comment by rpherbig** [comment]
E.g. https://github.com/rpherbig/dr-scripts/commits/master/profiles/Abius-setup.yaml (replace the character name as needed)

Abius (bard), Atere (bard), Doruktin (cleric), Elegoth (barb), Inkin (thief), Kawill (cleric), Khalei (thief), Kyandale (thief), Paeriluno (moon mage), Pennerohn (paladin), Phoerne (bard), Raddalaf (bard), Sheltim (barb), Sorjen (necro), Tamfall (war mage), Tekronn (paladin), Torgro (war mage)

I never did much with Traders or Empaths, but there are some lurking in the checked-in YAMLs.

**Comment by MahtraDR** [comment]
> 

The level 1 is exactly what I'm aiming for. @asechrest and I were just discussing this. We'll come up with a nice format, fully commented/documented, that just works for level 1. Basic instructions for gear acquisition and such. There is even a newcharacter script I think. "Run this script with 3 plat on the character, it'll grab you basic gear, and then use the level 1 yaml"

**Comment by MahtraDR** [comment]
Closing this as a topic. We can revisit whenif it's relevant again.
