### ISSUE TITLE
Controlled spell casting time

### ISSUE THREAD

**Issue by Aurayn** [rpherbig/dr-scripts#510]
Request to be able to control timing of BUFF spells.

USEAGE:
To be used instead of and \or in addition to waiting on the **_recast: #_** option which looks at the 'Active Spell' window. 

Would allow control of when the spell is cast after prepping so spells could be snapshot or after a certain number of seconds. 

Able to choose which spells use the **_recast_** option and which used the **_timed_** option so both are available in buffs.

**Comment by rpherbig** [comment]
Does recast_every meet this need? If not, how are they different?

**Comment by Aurayn** [comment]
Hey rpherbig, been looking, which section is that under in epedia?

**Comment by kamarcum** [comment]
It looks like it isn't documented. That's probably because it was a horrible hack I added for moonblades. `recast_every` will recast every N seconds where N is the configuration value. [Take a look at this moonblade example.](https://github.com/rpherbig/dr-scripts/blob/master/profiles/Mooselurk-setup.yaml#L156)

**Comment by rpherbig** [comment]
Is this still a problem?

**Comment by rcuhljr** [comment]
recast every is not what Aurayn is asking for. He wants a timer for the delay between preparing a spell and casting a spell, instead of waiting on full prep.

**Comment by rcuhljr** [comment]
`prep_time: #`  is now an optional field on spells.
