### ISSUE TITLE
dependency.lic does not handle case insensitively in windows environments well

### ISSUE THREAD

**Issue by vtcifer** [rpherbig/dr-scripts#5106]
At _least_ `help_me` will fail to fetch character yaml files when the case does not match what is expected (character name being first letter capitalized, all others lower case).

**Comment by MahtraDR** [comment]
This isn't a bug, and is expected behavior. Whilst Windows file systems aren't case insensitive by default, lich, and dependency are cross platform... Microsoft hosts a nice article on this topic for windows users for when they start working with wsl. It's very informative on the topic. https://docs.microsoft.com/en-us/windows/wsl/case-sensitivity

@rpherbig close?
