### ISSUE TITLE
[script] [remedy.lic] using `crafting_items_in_container` with mortar/bowl/etc causes remedies exit abnormally 

### ISSUE THREAD

**Issue by vtcifer** [rpherbig/dr-scripts#5179]
Caused because after  lowering to the ground it's no longer in the container:

```
[remedy]>put my book in my duffel bag
You put your book in your duffel bag.
> 
[remedy]>get my bowl from my duffel bag
> 
You get a large onyx bowl painted with tuberose blossoms from inside your duffel bag.
> 
[remedy]>lower ground
You lower the bowl and place it on the ground at your feet.
> 
[remedy]>tap ojhenik in duffel bag
You tap some crushed ojhenik inside your duffel bag.
> 
[remedy]>get my ojhenik from my duffel bag
You get some crushed ojhenik from inside your duffel bag.
> 
[remedy]>count my ojhenik
You count out 25 pieces of material there.
> 
[remedy]>combine my ojhenik
You must be holding both substances to combine them.  For more information, see HELP VERB COMBINE.
> 
[remedy]>put ojhenik in my bowl
You put your ojhenik in your onyx bowl.
> 
[remedy]>put my ojhenik in my duffel bag
What were you referring to?
> 
[remedy]>get my bowl from my duffel bag
What were you referring to?
> 
> 
[remedy: ]
[remedy: You seem to be missing: bowl]
--- Lich: remedy has exited.
```

**Comment by rpherbig** [comment]
@Dartellum

**Comment by Dartellum** [comment]
Weird it does not pick up the bowl for you. In theory, it should have picked the bowl up on line 203 `bput("get my #{@container}", 'You pick up', 'You get')`.

**Comment by asechrest** [comment]
I see the problem on this one. The method to get items is used for both getting the container (mortar, bowl, etc.) out of a yaml-specified `crafting_container` as well as to pick up the container when it is lowered at your feet. The problem arises when said container is listed under yaml setting `crafting_items_in_container` because this method honors that setting, which then will always try to get the container from that location, which is never at your feet.

I'll take a look at this one.

**Comment by asechrest** [comment]
@rpherbig Ok to close via #5338
