### ISSUE TITLE
hunting-buddy fails to exit combat-trainer when stop_on_low fires at beginning of hunt

### ISSUE THREAD

**Issue by Tirost** [rpherbig/dr-scripts#5814]
A situation occurs where my tarantula eats a skill listed under stop_on_low just as hunting-buddy/combat-trainer are beginning a hunt. The `***STATUS*** Stopping because skills dropped below learning threshold` messaging triggers, but the hunt doesn't stop. The hunt just continuously progresses without ever checking either time, stop_on or stop_on_low limits.

Log below:

https://pastebin.com/HxsL0uuk

**Comment by MahtraDR** [comment]
Could you please post your `hunting_info` settings for this hunt as well? Thanks!

**Comment by Tirost** [comment]
`hunting_info:
- :zone: black_apes
  :duration: 40
  stop_on:
  - First Aid
  - Staves
  stop_on_low:
  - Shield Usage
  - Evasion`
  
Thanks for looking into it, Mahtra.

**Comment by asechrest** [comment]
The following hunch was discussed in Discord, with Briarleigh and @vtcifer contributing:

In this instance, `hunting-buddy` immediately notices a `stop_on_low` threshold and calls the `$COMBAT_TRAINER.stop` method to set instance variable `@stop = true`. However, this may be _before_ combat trainer's initial setup, which sets `@stop = false` in preparation for the rest of the combat trainer run.

The current best idea, also courtesy of @vtcifer , is to build in logic in combat-trainer's `stop` method to wait until the script is initialized and `@running` before setting the stop variable so that it's not overwritten.

**Comment by MahtraDR** [comment]
After a bit of digging, this is the same problem as described here https://github.com/rpherbig/dr-scripts/pull/4849#issuecomment-811440402
