### ISSUE TITLE
Spare Gem Pouch not Switching when Full

### ISSUE THREAD

**Issue by wscherer420** [rpherbig/dr-scripts#611]
I have the Spare Gem Pouch settings in my setup file.  But during combat, my character won't switch to the spare gem pouch when the first is full.  Any ideas?

**Comment by wscherer420** [comment]
Combat Log:  Starts with last critter prior to pouch being full

http://pastebin.com/Ur2qwLTX

YAML File:   http://pastebin.com/Hr29dRPT

**Comment by rpherbig** [comment]
It looks like your pouch was untied, which has a different message than a tied pouch (`You've already got a wealth of gems in there!  You'd better tie it up before putting more gems inside.`).

Does tieing the pouch make it possible to add more gems to it?

Was it intentional that your pouch was untied?

At the end of the "switch to spare pouch" logic, it ties your new pouch. Is that a problem for you?

**Comment by rcuhljr** [comment]
Yes gem pouch tying makes it hold more gems, however it should probably work with untied pouches. I just didn't think about it because I only tie my pouches. If the pouch was untied the new one should just be closed, not tied.

**Comment by wscherer420** [comment]
I keep my Dark Gem Pouch on, and my spare Dark Gem Pouch in my Toolbag.  If i stow a Gem Pouch it goes into my Traveler's Pack.

Are you saying that if i have my spare gem pouch closed while inside the toolbag that it may fix this?

**Comment by rcuhljr** [comment]
No, you need to tie the pouches you're wearing.

**Comment by wscherer420** [comment]
ahhh.  Would it be possible to put a request to adjust the settings so that a tied pouch is not required?  I don't like tying my pouch because i'm unable to sell it as I'm not a trader.

**Comment by rcuhljr** [comment]
Yeah we'll do it sometime, although your local traders appreciate the trading exp of tied pouches :)

**Comment by rcuhljr** [comment]
Should be working, let us know if it does anything strange.
