### ISSUE TITLE
Crafting

### ISSUE THREAD

**Issue by Kaesken** [rpherbig/dr-scripts#6687]
So when my toons don't have enough coin to buy stuff, the script will stop and move on, however, it won't put away what was brought out in her hand.
For example:  the forge script she didn't have enough coin for the ingot so when it tried to get an ingot and there wasn't one, it would stop the script then move on to the next thing which I have set to Outfitting.  Then she's spamming trying to combine yarn with her forging hammer over and over again.

I tried to put "empty_hands" in the before dying do section but it didn't seem to work.  Is there any way that this can be fixed to put away any tools that was brought out if materials weren't found?

```
[forge]>get my diagonal-peen hammer
You get an iron diagonal-peen hammer from inside your purple backpack.
> 
[forge]>get my bronze ingot
What were you referring to?
> 
[forge: ]
[forge: You seem to be missing: bronze ingot]
All of your containers:

  a woven shoulder tote
  a heavy linen duffel bag
  a rugged purple backpack
  a laborer's drab cotton odaj
  an indigo gem pouch (closed)
[Use INVENTORY HELP for more options.]
> 
--- Lich: forge has exited.
--- Lich: go2 active.
[go2: ETA: 0:00:00 (3 rooms to move through)]
[go2]>go arch
```

**Comment by vtcifer** [comment]
Why are you out of money?

**Comment by Kaesken** [comment]
> Why are you out of money?

F2P unfortunately.  I managed to get my Empath to give her some coin to fix it to work around it.

**Comment by vtcifer** [comment]
> F2P unfortunately

That doesn't really answer the question.  

F2P have bank limits of 10 plat, but that is well above what would be expected/needed of any script.  Knowing _why_ you are out of money for that ingot gives us a better chance of advising how you can fix _your_ setup.

IMO, the critical issue here is the running out of money.  There are a **lot** of things that are not going to function well if get yourself into that situation.  It's akin to "well you could write combat trainer to better handle situations where you have put invalid gear / weapons, or you run out of ammo."

We could, but it doesn't really _solve_ the problem it just kicks the can down the road a little.   

In this situation you end up in an endless loop because forging is always going to be below the training threshold so it's going to keep getting called.

Similar issue with the invalid gear / lack of ammo. You won't be able to train those skills, so combat-trainer + hunting-buddy are going to run forever, even if we say, delete those skills from the training list so they're not attempted to be trained during that run of hb/ct.  Next cycle you get the same problem.  Those skills that couldn't be trained are below threshold, triggering hb/ct to go again, etc. 

These kind of error imo is more visible that something is _wrong_ in your setup, and can be addressed.

**Comment by Kaesken** [comment]
If anyone has a solution to where I can put "empty_hands" in a custom forge.lic, I'd really appreciate it.  I'm not going to ask this solution to be merged officially.  I have no issues keeping it as a custom script since the custom folder feature.  <3

My F2Ps are always running low on funds due to thiefs and such but I'm not going to complain about lack of coinage.

Thank you.
