### ISSUE TITLE
Hunting-Buddy should keep some cyclics running when it exits

### ISSUE THREAD

**Issue by jandersson** [rpherbig/dr-scripts#743]
I'm mainly thinking of the necromancer Rite of Grace spell when i write this. It is a cyclic that hides buffs that show on look/room description. This might be two separate threads of thought but either allow the player to specify cyclics they would like to not be de-activated or, when hunting buddy is cleaning up it could cast a waggle/buff set (which I could put rite of grace in).

**Comment by cynesis** [comment]
Transcendental buffs are not RELEASEable. Rite of Contrition, a Utility cyclic, removes Transcendental buffs before the spell timers expire. Rite of Grace, a Utility cyclic, hides Transcendental buffs while maintained, assuming the Necromancer takes the Liturgy metaspell. For the purposes of this comment, assume "Rite of Grace" implies RoG+Liturgy.

Rite of Grace hides an increasing number of Transcendental buffs based on how much mana is maintained. For example, 10-mana RoG hides three Transcendental buffs. Which, for most Necromancers, is an early goal: hiding Philosopher's Preservation, Butcher's Eye, and Ivory Mask.

Since combat-trainer maintains these buffs, but releases any cyclics during the cleanup process, the Necromancer is left with openly displaying tells between post-combat and the Transcendental buffs timing out and falling off.

Additionally, casting Transcendental buffs incurs Divine Outrage. This accrual is on a timer. Casting a Transcendental buff causes DO, but no more DO will accrue on subsequent Transcendental casts for X minutes. Practically speaking, Transcendental buffs are not training spells. However, Rite of Grace is the best Utility trainer Necromancers receive.

Conceptually, the easiest solution is to never release RoG. Hooking into the cyclic_training_spells routine would sufficiently release and recast to maintain training during down times. By and large, RoG should never be released given the current mechanics of buffing, both game mechanics and combat-trainer mechanics.

The more elegant solution is to only maintain RoG as long as Transcendental buffs exist, but I suspect that is either too much work for practically little gain, or too complicated as to be considered.

**Comment by jandersson** [comment]
As a suggestion, since it is the illegal spells that are the ones we want to release: We could make a new attribute in base-spells for each spell called `illegal` or `outlawed` and release only those.

**Comment by cynesis** [comment]
As long as cyclic spells can still be utilized during combat_training_spells routines and support exists for the case of returning from combat (never releasing "legal" cyclics) and starting a cyclic_training_spell routine using a different cyclic than the one maintained, I suspect that is going to be the quickest solution.
