### ISSUE TITLE
Getting stuck exiting RG/Leucro/Geni Wilds with bescort.

### ISSUE THREAD

**Issue by jayRyan24** [rpherbig/dr-scripts#817]
```
[go2]>north
You stomp north.
[Wilderness, Overgrown Path]
Though deep, the darkness isn't complete and the chirring sounds of insects fills the air.  Pressing in all around, a thicket of scrub and brush make passage difficult.  What little light there is comes from the east.  All other directions stare back with an opaque blackness as thick as tar.  You also see faint traces of an animal trail and a faint path.
Obvious paths: none.
>
[go2]>search
You search around for a moment.
Roundtime: 3 sec.
You don't find anything of interest here.
>
You lose track of where the animal trail is.
>
You lose track of where the faint path is.
>
[go2]>go path
I could not find what you were referring to.
>
[go2]>northeast
You can't go there.
>
[go2: move: failed]
[go2: restarting script...]
[go2: error: your current room was not found in the map database]
--- Lich: go2 has exited.
[hunting-buddy: Failed to navigate to room 1230, attempting again]
[hunting-buddy: In an unknown room, manually attempting to navigate to 1230]
[hunting-buddy: failed to find a matching room]
[hunting-buddy]>inv combat
All of your combat:

  some lumium mail gloves
  a blackened steel parry stick with sturdy steelsilk straps
  a lumium chain balaclava
  some lumium scale greaves
  a lumium chain shirt
  an azure-scale targe
  some steel spiked knuckles
  some steel knee spikes
  a pair of steel-toed stomping boots
  some steel elbow spikes
[Type INVENTORY HELP for more options]
>
--- Lich: hunting-buddy has exited.
--- Lich: safe-room active.
[safe-room]>health
Your body feels at full strength.
Your spirit feels full of life.
You have no significant injuries. 

>
[safe-room: ***STATUS*** No wounds, skipping healing]
--- Lich: safe-room has exited.
--- Lich: crossing-repair active.
[crossing-repair]>inv combat
All of your combat:

  some lumium mail gloves
  a blackened steel parry stick with sturdy steelsilk straps
  a lumium chain balaclava
  some lumium scale greaves
  a lumium chain shirt
  an azure-scale targe
  some steel spiked knuckles
  some steel knee spikes
  a pair of steel-toed stomping boots
  some steel elbow spikes
[Type INVENTORY HELP for more options]
>
[crossing-repair]>wealth kronars
  3 silver and 2 copper Kronars (302 copper Kronars).
>
[crossing-repair: In an unknown room, manually attempting to navigate to 1900]
[crossing-repair: failed to find a matching room]
[crossing-repair]>withdraw 1 platinum
You must be at a bank teller's window to withdraw money.
>
Vomax just arrived.
>
Vomax searches around for a moment.
>
[crossing-repair: *** No match was found after 15 seconds, dumping info]
[crossing-repair: messages seen length: 5]
[crossing-repair: message: You must be at a bank teller's window to withdraw money.]
[crossing-repair: message:  Monkey (very long time)]
[crossing-repair: message: Vomax just arrived.]
[crossing-repair: message: Vomax searches around for a moment.]
[crossing-repair: message:  Monkey (very long time)]
[crossing-repair: checked against [/The clerk count/i, /The clerk tells/i]]
[crossing-repair: In an unknown room, manually attempting to navigate to 19093]
[crossing-repair: failed to find a matching room]
>
You loosen the straps securing your parry stick and remove it.
>
[crossing-repair]>give my parry.stick to Catrox
The trail closes in behind Vomax and simply disappears.
Vomax went down faint traces of an animal trail.
>
What is it you're trying to give?
>
[crossing-repair: *** No match was found after 15 seconds, dumping info]
[crossing-repair: messages seen length: 4]
[crossing-repair: message: The trail closes in behind Vomax and simply disappears.]
[crossing-repair: message: Vomax went down faint traces of an animal trail.]
[crossing-repair: message: What is it you're trying to give?]
[crossing-repair: message:  Monkey (very long time)]
[crossing-repair: checked against [/There isn't a scratch on that/i, /I don't work on those here/i, /Just give it to me again/i, /You don't need to specify the object/i, /I will not repair something that isn't broken/i]]
[crossing-repair]>give my parry.stick to Catrox
>
What is it you're trying to give?
>
[crossing-repair]>stow my ticket
Stow what?  Type 'STOW HELP' for details.
>
[crossing-repair]>remove my elbow.spikes
You loosen the straps securing your elbow spikes and remove them.
>
[crossing-repair]>give my elbow.spikes to Catrox
What is it you're trying to give?
>
You've gained a new rank in your athletic ability.
>
You lose track of where the faint path is.
>
[crossing-repair: *** No match was found after 15 seconds, dumping info]
[crossing-repair: messages seen length: 5]
[crossing-repair: message: What is it you're trying to give?]
[crossing-repair: message:  Monkey (very long time)]
[crossing-repair: message: You've gained a new rank in your athletic ability.]
[crossing-repair: message: You lose track of where the faint path is.]
[crossing-repair: message:  Monkey (very long time)]
[crossing-repair: checked against [/There isn't a scratch on that/i, /I don't work on those here/i, /Just give it to me again/i, /You don't need to specify the object/i, /I will not repair something that isn't broken/i]]
[crossing-repair]>give my elbow.spikes to Catrox
What is it you're trying to give?
>
[crossing-repair]>stow my ticket
Stow what?  Type 'STOW HELP' for details.
>
[crossing-repair]>remove my stomping.boots
You need a free hand for that.
>
[crossing-repair: *** No match was found after 15 seconds, dumping info]
[crossing-repair: messages seen length: 3]
[crossing-repair: message: You need a free hand for that.]
[crossing-repair: message:  Monkey (very long time)]
[crossing-repair: message:  * Klines fades swiftly into the shadows.]
[crossing-repair: checked against [/stomping.*\bboots/i, /^You (get|sling|pull|work|loosen|slide|remove) /, /Remove what/i, /You aren't wearing that/i]]
>
A few fluffy clouds move into the sky.
>
YOU HAVE BEEN IDLE TOO LONG. PLEASE RESPOND.
>
[afk]>age
You are forty-six years old.
You are considered middle-aged.
You are aging at a normal rate for a Gor'Tog.
[Type AGE HELP for more options.]
>
Paladin Rileos just arrived.
>
Rileos searches around for a moment.
>
Paladin Rileos went down a faint path.
>
You lose track of where the animal trail is.
>
You lose track of where the faint path is.
>
You've gained a new rank in your knowledge of first aid.
>
Penetrator Endraig just arrived.
>
Endraig searches around for a moment.
>
The trail closes in behind Endraig and simply disappears.
Penetrator Endraig went down faint traces of an animal trail.
>
Yavash sets, slowly dropping below the horizon.
>
You lose track of where the faint path is.
>
YOU HAVE BEEN IDLE TOO LONG. PLEASE RESPOND.
>
[afk]>age
You are forty-six years old.
You are considered middle-aged.
You are aging at a normal rate for a Gor'Tog.
[Type AGE HELP for more options.]
```

**Comment by rpherbig** [comment]
Which hunting zone were you exiting (which is in your YAML)?

On Sep 17, 2016 10:04 AM, "jayRyan24" <notifications@github.com> wrote:

[go2]>north
You stomp north.
[Wilderness, Overgrown Path]
Though deep, the darkness isn't complete and the chirring sounds of
insects fills the air.  Pressing in all around, a thicket of scrub and
brush make passage difficult.  What little light there is comes from
the east.  All other directions stare back with an opaque blackness as
thick as tar.  You also see faint traces of an animal trail and a
faint path.
Obvious paths: none.
>
[go2]>search
You search around for a moment.
Roundtime: 3 sec.
You don't find anything of interest here.
>
You lose track of where the animal trail is.
>
You lose track of where the faint path is.
>
[go2]>go path
I could not find what you were referring to.
>
[go2]>northeast
You can't go there.
>
[go2: move: failed]
[go2: restarting script...]
[go2: error: your current room was not found in the map database]
--- Lich: go2 has exited.
[hunting-buddy: Failed to navigate to room 1230, attempting again]
[hunting-buddy: In an unknown room, manually attempting to navigate to 1230]
[hunting-buddy: failed to find a matching room]
[hunting-buddy]>inv combat
All of your combat:

  some lumium mail gloves
  a blackened steel parry stick with sturdy steelsilk straps
  a lumium chain balaclava
  some lumium scale greaves
  a lumium chain shirt
  an azure-scale targe
  some steel spiked knuckles
  some steel knee spikes
  a pair of steel-toed stomping boots
  some steel elbow spikes
[Type INVENTORY HELP for more options]
>
--- Lich: hunting-buddy has exited.
--- Lich: safe-room active.
[safe-room]>health
Your body feels at full strength.
Your spirit feels full of life.
You have no significant injuries.

>
[safe-room: ***STATUS*** No wounds, skipping healing]
--- Lich: safe-room has exited.
--- Lich: crossing-repair active.
[crossing-repair]>inv combat
All of your combat:

  some lumium mail gloves
  a blackened steel parry stick with sturdy steelsilk straps
  a lumium chain balaclava
  some lumium scale greaves
  a lumium chain shirt
  an azure-scale targe
  some steel spiked knuckles
  some steel knee spikes
  a pair of steel-toed stomping boots
  some steel elbow spikes
[Type INVENTORY HELP for more options]
>
[crossing-repair]>wealth kronars
  3 silver and 2 copper Kronars (302 copper Kronars).
>
[crossing-repair: In an unknown room, manually attempting to navigate to 1900]
[crossing-repair: failed to find a matching room]
[crossing-repair]>withdraw 1 platinum
You must be at a bank teller's window to withdraw money.
>
Vomax just arrived.
>
Vomax searches around for a moment.
>
[crossing-repair: *** No match was found after 15 seconds, dumping info]
[crossing-repair: messages seen length: 5]
[crossing-repair: message: You must be at a bank teller's window to
withdraw money.]
[crossing-repair: message:  Monkey (very long time)]
[crossing-repair: message: Vomax just arrived.]
[crossing-repair: message: Vomax searches around for a moment.]
[crossing-repair: message:  Monkey (very long time)]
[crossing-repair: checked against [/The clerk count/i, /The clerk tells/i]]
[crossing-repair: In an unknown room, manually attempting to navigate to 19093]
[crossing-repair: failed to find a matching room]
>
You loosen the straps securing your parry stick and remove it.
>
[crossing-repair]>give my parry.stick to Catrox
The trail closes in behind Vomax and simply disappears.
Vomax went down faint traces of an animal trail.
>
What is it you're trying to give?
>
[crossing-repair: *** No match was found after 15 seconds, dumping info]
[crossing-repair: messages seen length: 4]
[crossing-repair: message: The trail closes in behind Vomax and simply
disappears.]
[crossing-repair: message: Vomax went down faint traces of an animal trail.]
[crossing-repair: message: What is it you're trying to give?]
[crossing-repair: message:  Monkey (very long time)]
[crossing-repair: checked against [/There isn't a scratch on that/i,
/I don't work on those here/i, /Just give it to me again/i, /You don't
need to specify the object/i, /I will not repair something that isn't
broken/i]]
[crossing-repair]>give my parry.stick to Catrox
>
What is it you're trying to give?
>
[crossing-repair]>stow my ticket
Stow what?  Type 'STOW HELP' for details.
>
[crossing-repair]>remove my elbow.spikes
You loosen the straps securing your elbow spikes and remove them.
>
[crossing-repair]>give my elbow.spikes to Catrox
What is it you're trying to give?
>
You've gained a new rank in your athletic ability.
>
You lose track of where the faint path is.
>
[crossing-repair: *** No match was found after 15 seconds, dumping info]
[crossing-repair: messages seen length: 5]
[crossing-repair: message: What is it you're trying to give?]
[crossing-repair: message:  Monkey (very long time)]
[crossing-repair: message: You've gained a new rank in your athletic ability.]
[crossing-repair: message: You lose track of where the faint path is.]
[crossing-repair: message:  Monkey (very long time)]
[crossing-repair: checked against [/There isn't a scratch on that/i,
/I don't work on those here/i, /Just give it to me again/i, /You don't
need to specify the object/i, /I will not repair something that isn't
broken/i]]
[crossing-repair]>give my elbow.spikes to Catrox
What is it you're trying to give?
>
[crossing-repair]>stow my ticket
Stow what?  Type 'STOW HELP' for details.
>
[crossing-repair]>remove my stomping.boots
You need a free hand for that.
>
[crossing-repair: *** No match was found after 15 seconds, dumping info]
[crossing-repair: messages seen length: 3]
[crossing-repair: message: You need a free hand for that.]
[crossing-repair: message:  Monkey (very long time)]
[crossing-repair: message:  * Klines fades swiftly into the shadows.]
[crossing-repair: checked against [/stomping.*\bboots/i, /^You
(get|sling|pull|work|loosen|slide|remove) /, /Remove what/i, /You
aren't wearing that/i]]
>
A few fluffy clouds move into the sky.
>
YOU HAVE BEEN IDLE TOO LONG. PLEASE RESPOND.
>
[afk]>age
You are forty-six years old.
You are considered middle-aged.
You are aging at a normal rate for a Gor'Tog.
[Type AGE HELP for more options.]
>
Paladin Rileos just arrived.
>
Rileos searches around for a moment.
>
Paladin Rileos went down a faint path.
>
You lose track of where the animal trail is.
>
You lose track of where the faint path is.
>
You've gained a new rank in your knowledge of first aid.
>
Penetrator Endraig just arrived.
>
Endraig searches around for a moment.
>
The trail closes in behind Endraig and simply disappears.
Penetrator Endraig went down faint traces of an animal trail.
>
Yavash sets, slowly dropping below the horizon.
>
You lose track of where the faint path is.
>
YOU HAVE BEEN IDLE TOO LONG. PLEASE RESPOND.
>
[afk]>age
You are forty-six years old.
You are considered middle-aged.
You are aging at a normal rate for a Gor'Tog.
[Type AGE HELP for more options.]

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/rpherbig/dr-scripts/issues/817>, or mute the thread

**Comment by jayRyan24** [comment]
This happens when leaving all of those areas I mentioned, but this particular round was me leaving Rock Guardians.
