### ISSUE TITLE
Scholarship and go2 having Roundtime Issues

### ISSUE THREAD

**Issue by wscherer420** [rpherbig/dr-scripts#832]
I believe the issue i've been having with GO2 is related to the roundtime associated with the Scholarship Script.  I've been regularly having trouble getting onto the ferry or gondola on my new hunting routes south.  You can find the log of my recent event here.

http://pastebin.com/awS7KXeS

Any suggestions?

**Comment by rpherbig** [comment]
The cause seems pretty clear: scholarship started studying your book, tried to exit the boat while in roundtime, and never retried after roundtime was over.

I think there are two options: 1) stop using scholarship, or 2) we can try and update it to fix this behavior. But I don't know anything about it and it's from the lich repo, not ours.

Do you get enough Scholarship exp from listening to classes that you don't need to run this script?

**Comment by wscherer420** [comment]
yes i do, how would i cancel this script?

**Comment by wscherer420** [comment]
Oh so does having scholarship listed on Crossings-Training also activate Scholarship when waiting on go2?

**Comment by rpherbig** [comment]
No, `crossing-training` has its own way of training Scholarship. The script that is giving you problems comes from the lich repo and is run from escort (also from the lich repo).

There's no way to 'cancel' it short of deleting it.

**Comment by wscherer420** [comment]
Sorry to keep bothering, but i don't see the scholarship script listed in the repos and so i can't delete it.  Would deleting escort.lic do it? Do i need the escort.lic script to run go2?  I'm just now realizing that the repos scripts aren't made by you guys.  So maybe i have some unnecessary Repos scripts?

**Comment by rpherbig** [comment]
Is there a file called `scholarship.lic` in your ....../lich/scripts/ directory?

**Comment by wscherer420** [comment]
ah yes there was, i was looking through the stormfront window but on my actual computer there it was.  Thanks again for your help.
