### ISSUE TITLE
Meraud's Commune while hunting

### ISSUE THREAD

**Issue by drgabellia** [rpherbig/dr-scripts#912]
Would it be possible to "commune sense" before attempting Meraud's commune and NOT performing it if the area is already blessed?

Thanks!

> commune sense
> The blessing of Tamsine is with you.
> The power of Kertigen is channeling through you.
> A spark of Meraud's spirit is within the area.  <---  This shows area already blessed
> You are eager to better understand your relationship with the Immortals.
> Roundtime: 3 sec.

**Comment by drboldwin** [comment]
I'll jump on this if we want.  It's identical to how we check communes in theurgy.

**Comment by rpherbig** [comment]
Great!

**Comment by rpherbig** [comment]
@drboldwin Have you been working on this?

**Comment by rcuhljr** [comment]
Took care of this.

**Comment by drboldwin** [comment]
This is actually more complicated then that one line.  The commune lines when you commune sense can be one of many.  I had fixed this but not pushed it because I hadn't thought of how to respond to a non-meraud area without matching roundtime.

I had instead checked against Meraud and Meraud/'s and then roundtime.
