### ISSUE TITLE
Workorders should support non-knitting items

### ISSUE THREAD

**Issue by rpherbig** [rpherbig/dr-scripts#988]
In #977 a bunch of sewn and leather recipes were added. They aren't set to be used in workorders because the workorders script assumes all tailoring items are knitted. The sew script itself does handle sewn and leather items.

**Comment by dakre18** [comment]
When will this be addressed? i don't know if the sew script needs more work, but i was able to complete a bag that required sewing without any issues (running the script myself with type=sewing, not through workorders).

At least, would it be possible to mark certain items as knitted, sewing, or leather, and then only accept work orders for knitted items?

**Comment by Sarvatt** [comment]
it was fixed about a year ago when i turned on cloth workorders

**Comment by dakre18** [comment]
Then i'll put in a new issue. i just didn't want to add another open issue if this one wasn't completed for some reason.  The item i had trouble with was a cloth charm bag, it seems to be choosing the wrong type, from what i can tell.

**Comment by Sarvatt** [comment]
do you have a journeyman book? do you have outfitting_tools defined in your yaml?

**Comment by dakre18** [comment]
i have a master tailoring book, and i do have my outfitting_tools defined in my yaml. it tends to get stuck in 2 spots. 1. after studying the book, it gets the cloth, puts the cloth back in my pack, gets scissors, then tries to cut cloth with scissors. when it does start the charm bag, the loop it gets stuck in, it puts the scissors in my pack, gets the scissors out, and then tries to push bag with my needles.

That only happens when the workorder script calls the sew script.

**Comment by Tarhish** [comment]
Do you have a bag on your person?  I've sometimes entered that loop when sewing up rucksacks, since I have one in my inventory.

**Comment by dakre18** [comment]
i do have a bag on me, but why would it work when i manually run sew versus the workorder script starting it?

**Comment by Tarhish** [comment]
Because anything at all can throw DR's weird ordering of items into disarray.  For example my ;workorders worked on charm bags and small rucksacks just fine despite wearing both a bag and a rucksack, but if I did ANYTHING out of order DR might suddenly decide that 'push bag with needles' was no longer referring to my crafted bag, but instead referring to my worn watersilk bag and the script would hang.  There's not too much that can be done about that since it's so goofy and there's no text feedback about what it's done wrong.

We can make some changes to a few of the recipes to fix it when there's a unique adjective like the charm bag, but some of them just aren't going to work if you're wearing a version of that item and you'd have to use the workorder_recipes: feature to manually say 'look for these tailoring recipes only'

In the mean time try out going into scripts/data/base-recipes, search for charm bag and change the noun: to charm.bag.

So far small.rucksack is working well for me, so I'm betting that'll fix it until we see what else can be changed.  It won't even get erased until the recipes change for real so you don't have to do it again each day.

**Comment by dakre18** [comment]
workorder_recipes: sounds like a good workaround. didn't even think about something like that.

**Comment by Sarvatt** [comment]
+1 for adding adjectives to the crafting things, containers are only used 401+ ranks and its workorder specific. ;craft will just happily knit until 650 ranks.

**Comment by dakre18** [comment]
part of my problem may be that i grabbed the cloth and leather container techniques, as well as the knitted technique
